In [ ]:
import pandas as pd

In [ ]:
df_csv = pd.read_csv('/content/Churn_Modelling.csv')

In [ ]:
df_xml = pd.read_xml('/content/churn_modelling_xml.xml')

In [ ]:
df_xlsx = pd.read_excel('/content/churn_modelling_xlsx.xlsx')

In [ ]:
df_html = pd.read_html('/content/churn_modelling_html.html')

In [ ]:
df_json = pd.read_json('/content/churn_modelling_json.json')

In [ ]:
print(df_csv, df_xml, df_xlsx, df_html, df_json)

      RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42
1             2    15647311       Hill          608     Spain  Female   41
2             3    15619304       Onio          502    France  Female   42
3             4    15701354       Boni          699    France  Female   39
4             5    15737888   Mitchell          850     Spain  Female   43
...         ...         ...        ...          ...       ...     ...  ...
9995       9996    15606229   Obijiaku          771    France    Male   39
9996       9997    15569892  Johnstone          516    France    Male   35
9997       9998    15584532        Liu          709    France  Female   36
9998       9999    15682355  Sabbatini          772   Germany    Male   42
9999      10000    15628319     Walker          792    France  Female   28

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1
1          1   83807.86              1          0               1
2          8  159660.80              3          1               0
3          1       0.00              2          0               0
4          2  125510.82              1          1               1
...      ...        ...            ...        ...             ...
9995       5       0.00              2          1               0
9996      10   57369.61              1          1               1
9997       7       0.00              1          0               1
9998       3   75075.31              2          1               0
9999       4  130142.79              1          1               0

      EstimatedSalary  Exited
0           101348.88       1
1           112542.58       0
2           113931.57       1
3            93826.63       0
4            79084.10       0
...               ...     ...
9995         96270.64       0
9996        101699.77       0
9997         42085.58       1
9998         92888.52       1
9999         38190.78       0

[10000 rows x 14 columns]       index  RowNumber  CustomerId    Surname  CreditScore Geography  Gender  \
0         0          1    15634602   Hargrave          619    France  Female
1         1          2    15647311       Hill          608     Spain  Female
2         2          3    15619304       Onio          502    France  Female
3         3          4    15701354       Boni          699    France  Female
4         4          5    15737888   Mitchell          850     Spain  Female
...     ...        ...         ...        ...          ...       ...     ...
9995   9995       9996    15606229   Obijiaku          771    France    Male
9996   9996       9997    15569892  Johnstone          516    France    Male
9997   9997       9998    15584532        Liu          709    France  Female
9998   9998       9999    15682355  Sabbatini          772   Germany    Male
9999   9999      10000    15628319     Walker          792    France  Female

      Age  Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0      42       2       0.00              1          1               1
1      41       1   83807.86              1          0               1
2      42       8  159660.80              3          1               0
3      39       1       0.00              2          0               0
4      43       2  125510.82              1          1               1
...   ...     ...        ...            ...        ...             ...
9995   39       5       0.00              2          1               0
9996   35      10   57369.61              1          1               1
9997   36       7       0.00              1          0               1
9998   42       3   75075.31              2          1               0
9999   28       4  130142.79              1          1               0

      EstimatedSalary  Exited
0           101348.88       1
1           112542.58       0
2           113931.57       1
3            93826.63       0
4            79084.10       0
...               ...     ...
9995         96270.64       0
9996        101699.77       0
9997         42085.58       1
9998         92888.52       1
9999         38190.78       0

[10000 rows x 15 columns]       Unnamed: 0  RowNumber  CustomerId    Surname  CreditScore Geography  \
0              0          1    15634602   Hargrave          619    France
1              1          2    15647311       Hill          608     Spain
2              2          3    15619304       Onio          502    France
3              3          4    15701354       Boni          699    France
4              4          5    15737888   Mitchell          850     Spain
...          ...        ...         ...        ...          ...       ...
9995        9995       9996    15606229   Obijiaku          771    France
9996        9996       9997    15569892  Johnstone          516    France
9997        9997       9998    15584532        Liu          709    France
9998        9998       9999    15682355  Sabbatini          772   Germany
9999        9999      10000    15628319     Walker          792    France

      Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0     Female   42       2       0.00              1          1
1     Female   41       1   83807.86              1          0
2     Female   42       8  159660.80              3          1
3     Female   39       1       0.00              2          0
4     Female   43       2  125510.82              1          1
...      ...  ...     ...        ...            ...        ...
9995    Male   39       5       0.00              2          1
9996    Male   35      10   57369.61              1          1
9997  Female   36       7       0.00              1          0
9998    Male   42       3   75075.31              2          1
9999  Female   28       4  130142.79              1          1

      IsActiveMember  EstimatedSalary  Exited
0                  1        101348.88       1
1                  1        112542.58       0
2                  0        113931.57       1
3                  0         93826.63       0
4                  1         79084.10       0
...              ...              ...     ...
9995               0         96270.64       0
9996               1        101699.77       0
9997               1         42085.58       1
9998               0         92888.52       1
9999               0         38190.78       0

[10000 rows x 15 columns] [      Unnamed: 0  RowNumber  CustomerId    Surname  CreditScore Geography  \
0              0          1    15634602   Hargrave          619    France
1              1          2    15647311       Hill          608     Spain
2              2          3    15619304       Onio          502    France
3              3          4    15701354       Boni          699    France
4              4          5    15737888   Mitchell          850     Spain
...          ...        ...         ...        ...          ...       ...
9995        9995       9996    15606229   Obijiaku          771    France
9996        9996       9997    15569892  Johnstone          516    France
9997        9997       9998    15584532        Liu          709    France
9998        9998       9999    15682355  Sabbatini          772   Germany
9999        9999      10000    15628319     Walker          792    France

      Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0     Female   42       2       0.00              1          1
1     Female   41       1   83807.86              1          0
2     Female   42       8  159660.80              3          1
3     Female   39       1       0.00              2          0
4     Female   43       2  125510.82              1          1
...      ...  ...     ...        ...            ...        ...
9995    Male   39       5       0.00              2          1
9996    Male   35      10   57369.61              1          1
9997  Female   36       7       0.00              1          0
9998    Male   42       3   75075.31              2          1
9999  Female   28       4  130142.79              1          1

      IsActiveMember  EstimatedSalary  Exited
0                  1        101348.88       1
1                  1        112542.58       0
2                  0        113931.57       1
3                  0         93826.63       0
4                  1         79084.10       0
...              ...              ...     ...
9995               0         96270.64       0
9996               1        101699.77       0
9997               1         42085.58       1
9998               0         92888.52       1
9999               0         38190.78       0

[10000 rows x 15 columns]]       RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42
1             2    15647311       Hill          608     Spain  Female   41
2             3    15619304       Onio          502    France  Female   42
3             4    15701354       Boni          699    France  Female   39
4             5    15737888   Mitchell          850     Spain  Female   43
...         ...         ...        ...          ...       ...     ...  ...
9995       9996    15606229   Obijiaku          771    France    Male   39
9996       9997    15569892  Johnstone          516    France    Male   35
9997       9998    15584532        Liu          709    France  Female   36
9998       9999    15682355  Sabbatini          772   Germany    Male   42
9999      10000    15628319     Walker          792    France  Female   28

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1
1          1   83807.86              1          0               1
2          8  159660.80              3          1               0
3          1       0.00              2          0               0
4          2  125510.82              1          1               1
...      ...        ...            ...        ...             ...
9995       5       0.00              2          1               0
9996      10   57369.61              1          1               1
9997       7       0.00              1          0               1
9998       3   75075.31              2          1               0
9999       4  130142.79              1          1               0

      EstimatedSalary  Exited
0           101348.88       1
1           112542.58       0
2           113931.57       1
3            93826.63       0
4            79084.10       0
...               ...     ...
9995         96270.64       0
9996        101699.77       0
9997         42085.58       1
9998         92888.52       1
9999         38190.78       0

[10000 rows x 14 columns]

In [ ]:
df1.to_html('churn_modelling_html.html')

In [ ]:
df1.to_excel('churn_modelling_xlsx.xlsx')

In [ ]:
!pip install xlwt
import xlwt
df1.to_excel('churn_modelling_xls.xls')

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: xlwt in /usr/local/lib/python3.10/dist-packages (1.3.0)

<ipython-input-32-957ccbfcdb8a>:3: FutureWarning: As the xlwt package is no longer maintained, the xlwt engine will be removed in a future version of pandas. This is the only engine in pandas that supports writing in the xls format. Install openpyxl and write to an xlsx file instead. You can set the option io.excel.xls.writer to 'xlwt' to silence this warning. While this option is deprecated and will also raise a warning, it can be globally set and the warning suppressed.
  df1.to_excel('churn_modelling_xls.xls')

In [ ]:
df1.to_json('churn_modelling_json.json')

In [ ]:
df1.to_xml('churn_modelling_xml.xml')

# Python Pandas Series

In [ ]:
import pandas as pd

lst1 = [21,32,43,54,65,76,87,98,9,10]
ser1 = pd.Series(lst1)
print(ser1)
print(type(ser1))
ser1.ndim, ser1.shape, ser1.size

0    21
1    32
2    43
3    54
4    65
5    76
6    87
7    98
8     9
9    10
dtype: int64
<class 'pandas.core.series.Series'>

(1, (10,), 10)

In [ ]:
tup1 = ('a','b','c','d','e','f','g','h','i','j')
ser2 = pd.Series(tup1)
print(ser2)
print(type(ser2))
ser2.ndim, ser2.shape, ser2.size

0    a
1    b
2    c
3    d
4    e
5    f
6    g
7    h
8    i
9    j
dtype: object
<class 'pandas.core.series.Series'>

(1, (10,), 10)

In [ ]:
set1 = {1,2,3,4,5,6,7,8,9,0}
ser3 = pd.Series(set1)

TypeError: ignored

In [ ]:
dict1 = {'a':'b','c':'d','e':'f','g':'h','i':'j'}
ser4 = pd.Series(dict1)
print(ser4)
print(type(ser4))
ser4.dtypes, ser4.shape, ser4.size, ser4.ndim

a    b
c    d
e    f
g    h
i    j
dtype: object
<class 'pandas.core.series.Series'>

(dtype('O'), (5,), 5, 1)

In [ ]:
str1 = 'Python Programming'
ser5 = pd.Series(str1)
print(ser5)
print(type(ser5))
ser5.ndim, ser5.dtypes, ser5.shape, ser5.size

0    Python Programming
dtype: object
<class 'pandas.core.series.Series'>

(1, dtype('O'), (1,), 1)

In [ ]:
ser1.dtypes, ser2.dtypes, ser4.dtypes, ser5.dtypes

(dtype('int64'), dtype('O'), dtype('O'), dtype('O'))

In [ ]:
ser1.shape, ser2.shape, ser4.shape, ser5.shape

((10,), (10,), (5,), (1,))

In [ ]:
ser1.size, ser2.size, ser4.size, ser5.size

(10, 10, 5, 1)

In [ ]:
# Series.itemsize is deprecated and will be removed in a future version
ser1.itemsize, ser2.itemsize, ser4.itemsize, ser5.itemsize

AttributeError: ignored

In [ ]:
ser1.nbytes, ser2.nbytes, ser4.nbytes, ser5.nbytes

(80, 80, 40, 8)

In [ ]:
ser1.ndim, ser2.ndim, ser4.ndim, ser5.ndim

(1, 1, 1, 1)

In [ ]:
ser1.count(), ser2.count(), ser4.count(), ser5.count()

(10, 10, 5, 1)

In [ ]:
len(ser1), len(ser2), len(ser4), len(ser5), len(str1)

(10, 10, 5, 1, 18)

In [ ]:
ser1, lst1

(0    21
 1    32
 2    43
 3    54
 4    65
 5    76
 6    87
 7    98
 8     9
 9    10
 dtype: int64,
 [21, 32, 43, 54, 65, 76, 87, 98, 9, 10])

In [ ]:
ser6 = pd.Series(lst1, index=[11,22,33,44,55,66,77,88,99,110])
print(ser6)
print(type(ser6))
ser6.ndim, ser6.size , ser6.nbytes , ser6.shape , len(ser6) , ser6.count() , ser6.dtypes

11     21
22     32
33     43
44     54
55     65
66     76
77     87
88     98
99      9
110    10
dtype: int64
<class 'pandas.core.series.Series'>

(1, 10, 80, (10,), 10, 10, dtype('int64'))

In [ ]:
ser6

11     21
22     32
33     43
44     54
55     65
66     76
77     87
88     98
99      9
110    10
dtype: int64

In [ ]:
ser6.index = ['a','b','c','d','e','f','g','h', 'i', 'j']

In [ ]:
ser6

a    21
b    32
c    43
d    54
e    65
f    76
g    87
h    98
i     9
j    10
dtype: int64

In [ ]:
ser6, ser6[:], ser6[:5], ser6[3:7]

(a    21
 b    32
 c    43
 d    54
 e    65
 f    76
 g    87
 h    98
 i     9
 j    10
 dtype: int64,
 a    21
 b    32
 c    43
 d    54
 e    65
 f    76
 g    87
 h    98
 i     9
 j    10
 dtype: int64,
 a    21
 b    32
 c    43
 d    54
 e    65
 dtype: int64,
 d    54
 e    65
 f    76
 g    87
 dtype: int64)

In [ ]:
ser6

a    21
b    32
c    43
d    54
e    65
f    76
g    87
h    98
i     9
j    10
dtype: int64

In [ ]:
cp_ser6 = ser6.copy()

In [ ]:
cp_ser6

a    21
b    32
c    43
d    54
e    65
f    76
g    87
h    98
i     9
j    10
dtype: int64

In [ ]:
ser7 = cp_ser6.append(ser6)

<ipython-input-38-1113602d82b5>:1: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ser7 = cp_ser6.append(ser6)

In [ ]:
ser7

a    21
b    32
c    43
d    54
e    65
f    76
g    87
h    98
i     9
j    10
a    21
b    32
c    43
d    54
e    65
f    76
g    87
h    98
i     9
j    10
dtype: int64

In [ ]:
ser7.drop('j', inplace=True)
ser7

a    21
b    32
c    43
d    54
e    65
f    76
g    87
h    98
i     9
a    21
b    32
c    43
d    54
e    65
f    76
g    87
h    98
i     9
dtype: int64

In [ ]:
ser6.mean()

49.5

In [ ]:
ser6.median()

48.5

In [ ]:
ser6.mode()

0     9
1    10
2    21
3    32
4    43
5    54
6    65
7    76
8    87
9    98
dtype: int64

#**File Handling**

    "r" - Read - Default value. Opens a file for reading, error if the file does not exist

    "a" - Append - Opens a file for appending, creates the file if it does not exist

    "w" - Write - Opens a file for writing, creates the file if it does not exist

    "x" - Create - Creates the specified file, returns an error if the file exists

    "t" - Text - Default value. Text mode

    "b" - Binary - Binary mode (e.g. images)

In [ ]:
# "x" - Create - Creates the specified file, returns an error if the file exists

f = open('myfilename1.txt', 'x')

In [ ]:
# "w" - Write - Opens a file for writing, creates the file if it does not exist

f = open('myfilename1.txt', 'w')
f.write('this is first statement in write mode')
f.close

f = open('myfilename1.txt', 'r')
print(f.read())

this is first statement in write mode

In [ ]:
# "a" - Append - Opens a file for appending, creates the file if it does not exist

f = open('myfilename1.txt', 'a')
f.write('this is second statement in append mode')
f.close

f = open('myfilename1.txt', 'r')
print(f.read())

this is first statement in write modethis is second statement in append mode

In [ ]:
# Inbuilt Exceptions
# User Define Exceptions

In [ ]:
lst1 = [1,92,83,74,65,56,47,38,29,10]

lst_iter = iter(lst1)

print(next(lst_iter))
print(next(lst_iter))
print(next(lst_iter))
print(next(lst_iter))
print(next(lst_iter))
print(next(lst_iter))
print(next(lst_iter))
print(next(lst_iter))
print(next(lst_iter))
print(next(lst_iter))
print(next(lst_iter))

In [ ]:
lst1 = [1,92,83,74,65,56,47,38,29,10]

lst_iter = iter(lst1)

try:
  print(next(lst_iter))
  print(next(lst_iter))
  print(next(lst_iter))
  print(next(lst_iter))
  print(next(lst_iter))
  print(next(lst_iter))
  print(next(lst_iter))
  print(next(lst_iter))
  print(next(lst_iter))
  print(next(lst_iter))
  print(next(lst_iter))

except StopIteration as si:
  print('StopIteration ', si)  
except Exception as e:
  print('Universal Exception ', e)

In [ ]:
# super() function

class Alpha:
	classvar1 = "classvar1 - Class Alpha - Class local variable"
	def __init__(self):
		self.var1 = "self.var1 - Class Alpha - Constructor or __init__ function"
		self.classvar1 = "self.classvar1 - Class Alpha - Instance variable"

class Beta(Alpha):
  classvar1 = "Class Beta - Class local variable"
  def __init__(self):
    
    self.var1 = "self.var1 - Class Beta - Constructor or __init__ function"
    self.classvar1 = "self.classvar1 - Class Beta - Instance variable"
    print('self.var1 ', self.var1)
    print('self.classvar1 ', self.classvar1)
    super().__init__()

a = Alpha()
b = Beta()

print(b.classvar1,b.var1)

self.var1  self.var1 - Class Beta - Constructor or __init__ function
self.classvar1  self.classvar1 - Class Beta - Instance variable
self.classvar1 - Class Alpha - Instance variable self.var1 - Class Alpha - Constructor or __init__ function

In [ ]:
a = 10
b = 20

print(a)
print(b)

a = -1947
b = -1989

print(a)
print(b)

10
20
-1947
-1989

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/Churn_Modelling.csv')
df

In [ ]:
df.to_html('Churn_Modelling_HTML.html')

In [ ]:
lst1 = ['apple','banana','cherries','dates','eggfruits','fig']
ser1 = pd.Series(lst1)
print(ser1)
print(type(ser1))

0        apple
1       banana
2     cherries
3        dates
4    eggfruits
5          fig
dtype: object
<class 'pandas.core.series.Series'>

In [ ]:
ser1.index = ['Ahmadabad',
              'Birmingham',
              'CAIRO',
              'DAMASCUS',
              'Ecatepec',
              'Faisalabad']
print(type(ser1))

<class 'pandas.core.series.Series'>

In [ ]:
ser1

Ahmadabad         apple
Birmingham       banana
CAIRO          cherries
DAMASCUS          dates
Ecatepec      eggfruits
Faisalabad          fig
dtype: object

In [ ]:
ser1['Ahmadabad'], ser1['Birmingham'], ser1['CAIRO'], ser1['DAMASCUS'], ser1['Ecatepec'], ser1['Faisalabad']

('apple', 'banana', 'cherries', 'dates', 'eggfruits', 'fig')

In [ ]:
ser1[0], ser1[1], ser1[2], ser1[3], ser1[4], ser1[5]

('apple', 'banana', 'cherries', 'dates', 'eggfruits', 'fig')

In [ ]:
ser1['CAIRO':'Faisalabad']

CAIRO          cherries
DAMASCUS          dates
Ecatepec      eggfruits
Faisalabad          fig
dtype: object

In [ ]:
ser1.iloc['CAIRO':'Faisalabad']

TypeError: ignored

In [ ]:
ser1.iloc[2:5]

CAIRO        cherries
DAMASCUS        dates
Ecatepec    eggfruits
dtype: object

In [ ]:
ser1

Ahmadabad         apple
Birmingham       banana
CAIRO          cherries
DAMASCUS          dates
Ecatepec      eggfruits
Faisalabad          fig
dtype: object

In [ ]:
ser1[:]

Ahmadabad         apple
Birmingham       banana
CAIRO          cherries
DAMASCUS          dates
Ecatepec      eggfruits
Faisalabad          fig
dtype: object

In [ ]:
ser1[::-1]

Faisalabad          fig
Ecatepec      eggfruits
DAMASCUS          dates
CAIRO          cherries
Birmingham       banana
Ahmadabad         apple
dtype: object

In [ ]:
import pandas as pd
lst1 = [90,91,82,73,64,55,46,37,28,19]
df1 = pd.DataFrame(lst1)
print(df1)
print(type(df1)) # 'pandas.core.frame.DataFrame'
df1.ndim, df1.shape, df1.size

    0
0  90
1  91
2  82
3  73
4  64
5  55
6  46
7  37
8  28
9  19
<class 'pandas.core.frame.DataFrame'>

(2, (10, 1), 10)

In [ ]:
df1[0]

0    90
1    91
2    82
3    73
4    64
5    55
6    46
7    37
8    28
9    19
Name: 0, dtype: int64

In [ ]:
df1[1] = ['a0','b1','c2','d3','e4','f5','g6','h7','i8','j9']
df1

    0   1
0  90  a0
1  91  b1
2  82  c2
3  73  d3
4  64  e4
5  55  f5
6  46  g6
7  37  h7
8  28  i8
9  19  j9

In [ ]:
df1[2] = ('apple','ball','cat','dog','elephant','fish','grapes','horse','ink pot','jute')
df1

    0   1         2
0  90  a0     apple
1  91  b1      ball
2  82  c2       cat
3  73  d3       dog
4  64  e4  elephant
5  55  f5      fish
6  46  g6    grapes
7  37  h7     horse
8  28  i8   ink pot
9  19  j9      jute

In [ ]:
df1.columns = ['col1','col2','col3']
df1

   col1 col2      col3
0    90   a0     apple
1    91   b1      ball
2    82   c2       cat
3    73   d3       dog
4    64   e4  elephant
5    55   f5      fish
6    46   g6    grapes
7    37   h7     horse
8    28   i8   ink pot
9    19   j9      jute

In [ ]:
df1.index = ['row1','row2','row3','row4','row5','row6','row7','row8','row9','row10']
df1

       col1 col2      col3
row1     90   a0     apple
row2     91   b1      ball
row3     82   c2       cat
row4     73   d3       dog
row5     64   e4  elephant
row6     55   f5      fish
row7     46   g6    grapes
row8     37   h7     horse
row9     28   i8   ink pot
row10    19   j9      jute

In [ ]:
set1 = {1,1,1,2,2,2,3,3,3,4,4,4,5,5,5,6,6,6,7,7,7,8,8,8,9,9,9}
df2 = pd.DataFrame(set1)
df2

   0
0  1
1  2
2  3
3  4
4  5
5  6
6  7
7  8
8  9

In [ ]:
dict1 = {'alphabate a': [1,2,3,4,5,6,7,8,9,10],
         'alphabate b': (21,22,23,24,25,26,27,28,29,30),
         'alphabate c': [51,52,53,54,55,56,57,58,59,60],
         'alphabate d': (61,62,63,64,65,66,67,68,69,70),
         'alphabate e': [91,92,93,94,95,96,97,98,99,100]
         }
df3 = pd.DataFrame(dict1)
df3

   alphabate a  alphabate b  alphabate c  alphabate d  alphabate e
0            1           21           51           61           91
1            2           22           52           62           92
2            3           23           53           63           93
3            4           24           54           64           94
4            5           25           55           65           95
5            6           26           56           66           96
6            7           27           57           67           97
7            8           28           58           68           98
8            9           29           59           69           99
9           10           30           60           70          100

In [ ]:
import pandas as pd
data = [
	{'a': 1, 'b': 2},
	{'a': 5, 'b': 10, 'c': 20},
	{'a': 35, 'b': 40, 'c': 50, 'd': 66},
	{'a': 3, 'b': 4, 'c': 5, 'd': 6, 'e':7},
	{'a': 13, 'b': 24, 'c': 35, 'd': 46, 'e':57, 'f':66}
	]
df_1 = pd.DataFrame(data)
#df_2 = pd.DataFrame(data, index=['row1'], columns=['col1'])
#df_3 = pd.DataFrame(data, index=['row1','row2'], columns=['col1','col2'])
#df_4 = pd.DataFrame(data, index=['row1','row2','row3'], columns=['col1','col2','col3'])
#df_5 = pd.DataFrame(data, index=['row1','row2','row3','row4'], columns=['col1','col2','col3','col4'])
#df_6 = pd.DataFrame(data, index=['row1','row2','row3','row4','row5'], columns=['col1','col2','col3','col4','col5'])
df_7 = pd.DataFrame(data, index=['row1','row2','row3','row4','row5'], columns=['col1','col2','col3','col4','col5','col6'])
#df_8 = pd.DataFrame(data, index=['row1','row2','row3','row4','row5','row6','row7'], columns=['col1','col2','col3','col4','col5','col6','col7'])
#df_9 = pd.DataFrame(data, index=['row1','row2','row3','row4','row5','row6','row7','row8'], columns=['col1','col2','col3','col4','col5','col6','col7','col8'])
print(df_1)
print(df_7)

    a   b     c     d     e     f
0   1   2   NaN   NaN   NaN   NaN
1   5  10  20.0   NaN   NaN   NaN
2  35  40  50.0  66.0   NaN   NaN
3   3   4   5.0   6.0   7.0   NaN
4  13  24  35.0  46.0  57.0  66.0
      col1  col2  col3  col4  col5  col6
row1   NaN   NaN   NaN   NaN   NaN   NaN
row2   NaN   NaN   NaN   NaN   NaN   NaN
row3   NaN   NaN   NaN   NaN   NaN   NaN
row4   NaN   NaN   NaN   NaN   NaN   NaN
row5   NaN   NaN   NaN   NaN   NaN   NaN

In [ ]:
import pandas as pd
data = [
	{'a': 1, 'b': 2},
	{'a': 5, 'b': 10, 'c': 20},
	{'a': 35, 'b': 40, 'c': 50, 'd': 66},
	{'a': 3, 'b': 4, 'c': 5, 'd': 6, 'e':7},
	{'a': 13, 'b': 24, 'c': 35, 'd': 46, 'e':57, 'f':66}
	]
df_1 = pd.DataFrame(data)
#df_7 = pd.DataFrame(data, index=['row1','row2','row3','row4','row5'], columns=['col1','col2','col3','col4','col5','col6'])
print(df_1)
#print(df_7)

    a   b     c     d     e     f
0   1   2   NaN   NaN   NaN   NaN
1   5  10  20.0   NaN   NaN   NaN
2  35  40  50.0  66.0   NaN   NaN
3   3   4   5.0   6.0   7.0   NaN
4  13  24  35.0  46.0  57.0  66.0

In [ ]:
dict1 = {
    'A': pd.Series([1,2,3], index=['a','b','c']),
    'B': pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])
}

#print(dict1)
df_dict1 = pd.DataFrame(dict1)
df_dict1

     A  B
a  1.0  1
b  2.0  2
c  3.0  3
d  NaN  4
e  NaN  5

In [ ]:
dict2 = {'Col1': pd.Series([1,2,3], index=['apple','banana','cherries']),
         'Col2': pd.Series([1,2,3,4,5], index=['dates','eggfruit','fig','grapes','honeyfruit'])}
df_dict2 = pd.DataFrame(dict2)
df_dict2

            Col1  Col2
apple        1.0   NaN
banana       2.0   NaN
cherries     3.0   NaN
dates        NaN   1.0
eggfruit     NaN   2.0
fig          NaN   3.0
grapes       NaN   4.0
honeyfruit   NaN   5.0

In [ ]:
dict2 = {'Col1': pd.Series([1,2,3], index=['apple','banana','cherries']),
         'Col2': pd.Series([1,2,3,4,5], index=['dates','eggfruit','fig','grapes','honeyfruit']),
         'Col3': pd.Series([1,3,5], index=['dates','fig','honeyfruit']),
         'Col4': pd.Series([1,2,3,4,5,6,7,8], index=['apple','banana','cherries','dates','eggfruit','fig','grapes','honeyfruit']),
         'Col5': pd.Series([])}
df_dict2 = pd.DataFrame(dict2)
df_dict2

<ipython-input-6-ba6aff6d2e6a>:5: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  'Col5': pd.Series([])}

            Col1  Col2  Col3  Col4  Col5
apple        1.0   NaN   NaN     1   NaN
banana       2.0   NaN   NaN     2   NaN
cherries     3.0   NaN   NaN     3   NaN
dates        NaN   1.0   1.0     4   NaN
eggfruit     NaN   2.0   NaN     5   NaN
fig          NaN   3.0   3.0     6   NaN
grapes       NaN   4.0   NaN     7   NaN
honeyfruit   NaN   5.0   5.0     8   NaN

In [ ]:
dates = pd.date_range(start='27-May-2023', end='02-Jun-2023')
dates

DatetimeIndex(['2023-05-27', '2023-05-28', '2023-05-29', '2023-05-30',
               '2023-05-31', '2023-06-01', '2023-06-02'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
dates = pd.date_range('today', periods=7)
dates

DatetimeIndex(['2023-05-31 00:21:03.584074', '2023-06-01 00:21:03.584074',
               '2023-06-02 00:21:03.584074', '2023-06-03 00:21:03.584074',
               '2023-06-04 00:21:03.584074', '2023-06-05 00:21:03.584074',
               '2023-06-06 00:21:03.584074'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
dates = pd.date_range(start='27-May-2003', periods=7)
dates

DatetimeIndex(['2003-05-27', '2003-05-28', '2003-05-29', '2003-05-30',
               '2003-05-31', '2003-06-01', '2003-06-02'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
import numpy as np
val = np.random.random((7,7))
val

array([[0.17261392, 0.29486581, 0.69215411, 0.33706952, 0.27966126,
        0.04420303, 0.57987912],
       [0.50519983, 0.25810715, 0.34445887, 0.29780948, 0.100074  ,
        0.56660821, 0.70994139],
       [0.52722596, 0.94525554, 0.84866491, 0.42034106, 0.62945012,
        0.98147457, 0.01102755],
       [0.94895073, 0.40689485, 0.03281126, 0.30986624, 0.93089565,
        0.62036639, 0.81535855],
       [0.10427647, 0.85342041, 0.34165288, 0.27538422, 0.0347879 ,
        0.76976484, 0.8494205 ],
       [0.05308774, 0.58171259, 0.70131923, 0.9351601 , 0.29590811,
        0.9683327 , 0.62851999],
       [0.71138744, 0.78829379, 0.91825152, 0.0067718 , 0.57718381,
        0.2658706 , 0.57012032]])

In [ ]:
df_matrix1 = pd.DataFrame(val, index=dates)
df_matrix1

,0,1,2,3,4,5,6
2023-05-27,0.172614,0.294866,0.692154,0.337070,0.279661,0.044203,0.579879
2023-05-28,0.505200,0.258107,0.344459,0.297809,0.100074,0.566608,0.709941
2023-05-29,0.527226,0.945256,0.848665,0.420341,0.629450,0.981475,0.011028
2023-05-30,0.948951,0.406895,0.032811,0.309866,0.930896,0.620366,0.815359
2023-05-31,0.104276,0.853420,0.341653,0.275384,0.034788,0.769765,0.849421
2023-06-01,0.053088,0.581713,0.701319,0.935160,0.295908,0.968333,0.628520
2023-06-02,0.711387,0.788294,0.918252,0.006772,0.577184,0.265871,0.570120

In [ ]:
df_matrix1.columns = ['col1','col2','col3','col4','col5','col6','col7']

In [ ]:
df_matrix1

,col1,col2,col3,col4,col5,col6,col7
2023-05-27,0.172614,0.294866,0.692154,0.337070,0.279661,0.044203,0.579879
2023-05-28,0.505200,0.258107,0.344459,0.297809,0.100074,0.566608,0.709941
2023-05-29,0.527226,0.945256,0.848665,0.420341,0.629450,0.981475,0.011028
2023-05-30,0.948951,0.406895,0.032811,0.309866,0.930896,0.620366,0.815359
2023-05-31,0.104276,0.853420,0.341653,0.275384,0.034788,0.769765,0.849421
2023-06-01,0.053088,0.581713,0.701319,0.935160,0.295908,0.968333,0.628520
2023-06-02,0.711387,0.788294,0.918252,0.006772,0.577184,0.265871,0.570120

In [ ]:
df_matrix1.index

DatetimeIndex(['2023-05-27', '2023-05-28', '2023-05-29', '2023-05-30',
               '2023-05-31', '2023-06-01', '2023-06-02'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
df_matrix1.columns

Index(['col1', 'col2', 'col3', 'col4', 'col5', 'col6', 'col7'], dtype='object')

In [ ]:
df_matrix1.head()

,col1,col2,col3,col4,col5,col6,col7
2023-05-27,0.172614,0.294866,0.692154,0.337070,0.279661,0.044203,0.579879
2023-05-28,0.505200,0.258107,0.344459,0.297809,0.100074,0.566608,0.709941
2023-05-29,0.527226,0.945256,0.848665,0.420341,0.629450,0.981475,0.011028
2023-05-30,0.948951,0.406895,0.032811,0.309866,0.930896,0.620366,0.815359
2023-05-31,0.104276,0.853420,0.341653,0.275384,0.034788,0.769765,0.849421

In [ ]:
df_matrix1.head(2)

,col1,col2,col3,col4,col5,col6,col7
2023-05-27,0.172614,0.294866,0.692154,0.337070,0.279661,0.044203,0.579879
2023-05-28,0.505200,0.258107,0.344459,0.297809,0.100074,0.566608,0.709941

In [ ]:
df_matrix1.tail()

,col1,col2,col3,col4,col5,col6,col7
2023-05-29,0.527226,0.945256,0.848665,0.420341,0.629450,0.981475,0.011028
2023-05-30,0.948951,0.406895,0.032811,0.309866,0.930896,0.620366,0.815359
2023-05-31,0.104276,0.853420,0.341653,0.275384,0.034788,0.769765,0.849421
2023-06-01,0.053088,0.581713,0.701319,0.935160,0.295908,0.968333,0.628520
2023-06-02,0.711387,0.788294,0.918252,0.006772,0.577184,0.265871,0.570120

In [ ]:
df_matrix1.tail(2)

,col1,col2,col3,col4,col5,col6,col7
2023-06-01,0.053088,0.581713,0.701319,0.935160,0.295908,0.968333,0.62852
2023-06-02,0.711387,0.788294,0.918252,0.006772,0.577184,0.265871,0.57012

In [ ]:
df_matrix1.dtypes

col1    float64
col2    float64
col3    float64
col4    float64
col5    float64
col6    float64
col7    float64
dtype: object

In [ ]:
df_matrix1.info

<bound method DataFrame.info of                 col1      col2      col3      col4      col5      col6  \
2023-05-27  0.172614  0.294866  0.692154  0.337070  0.279661  0.044203
2023-05-28  0.505200  0.258107  0.344459  0.297809  0.100074  0.566608
2023-05-29  0.527226  0.945256  0.848665  0.420341  0.629450  0.981475
2023-05-30  0.948951  0.406895  0.032811  0.309866  0.930896  0.620366
2023-05-31  0.104276  0.853420  0.341653  0.275384  0.034788  0.769765
2023-06-01  0.053088  0.581713  0.701319  0.935160  0.295908  0.968333
2023-06-02  0.711387  0.788294  0.918252  0.006772  0.577184  0.265871

                col7
2023-05-27  0.579879
2023-05-28  0.709941
2023-05-29  0.011028
2023-05-30  0.815359
2023-05-31  0.849421
2023-06-01  0.628520
2023-06-02  0.570120  >

In [ ]:
df_matrix1.describe

<bound method NDFrame.describe of                 col1      col2      col3      col4      col5      col6  \
2023-05-27  0.172614  0.294866  0.692154  0.337070  0.279661  0.044203
2023-05-28  0.505200  0.258107  0.344459  0.297809  0.100074  0.566608
2023-05-29  0.527226  0.945256  0.848665  0.420341  0.629450  0.981475
2023-05-30  0.948951  0.406895  0.032811  0.309866  0.930896  0.620366
2023-05-31  0.104276  0.853420  0.341653  0.275384  0.034788  0.769765
2023-06-01  0.053088  0.581713  0.701319  0.935160  0.295908  0.968333
2023-06-02  0.711387  0.788294  0.918252  0.006772  0.577184  0.265871

                col7
2023-05-27  0.579879
2023-05-28  0.709941
2023-05-29  0.011028
2023-05-30  0.815359
2023-05-31  0.849421
2023-06-01  0.628520
2023-06-02  0.570120  >

In [ ]:
df_matrix1.describe()

           col1      col2      col3      col4      col5      col6      col7
count  7.000000  7.000000  7.000000  7.000000  7.000000  7.000000  7.000000
mean   0.431820  0.589793  0.554188  0.368915  0.406852  0.602374  0.594895
std    0.336150  0.278619  0.321697  0.280693  0.319952  0.349298  0.279730
min    0.053088  0.258107  0.032811  0.006772  0.034788  0.044203  0.011028
25%    0.138445  0.350880  0.343056  0.286597  0.189868  0.416239  0.575000
50%    0.505200  0.581713  0.692154  0.309866  0.295908  0.620366  0.628520
75%    0.619307  0.820857  0.774992  0.378705  0.603317  0.869049  0.762650
max    0.948951  0.945256  0.918252  0.935160  0.930896  0.981475  0.849421

In [ ]:
df_matrix1

,col1,col2,col3,col4,col5,col6,col7
2023-05-27,0.172614,0.294866,0.692154,0.337070,0.279661,0.044203,0.579879
2023-05-28,0.505200,0.258107,0.344459,0.297809,0.100074,0.566608,0.709941
2023-05-29,0.527226,0.945256,0.848665,0.420341,0.629450,0.981475,0.011028
2023-05-30,0.948951,0.406895,0.032811,0.309866,0.930896,0.620366,0.815359
2023-05-31,0.104276,0.853420,0.341653,0.275384,0.034788,0.769765,0.849421
2023-06-01,0.053088,0.581713,0.701319,0.935160,0.295908,0.968333,0.628520
2023-06-02,0.711387,0.788294,0.918252,0.006772,0.577184,0.265871,0.570120

In [ ]:
df_matrix1.sort_values(by='col1')

,col1,col2,col3,col4,col5,col6,col7
2023-06-01,0.053088,0.581713,0.701319,0.935160,0.295908,0.968333,0.628520
2023-05-31,0.104276,0.853420,0.341653,0.275384,0.034788,0.769765,0.849421
2023-05-27,0.172614,0.294866,0.692154,0.337070,0.279661,0.044203,0.579879
2023-05-28,0.505200,0.258107,0.344459,0.297809,0.100074,0.566608,0.709941
2023-05-29,0.527226,0.945256,0.848665,0.420341,0.629450,0.981475,0.011028
2023-06-02,0.711387,0.788294,0.918252,0.006772,0.577184,0.265871,0.570120
2023-05-30,0.948951,0.406895,0.032811,0.309866,0.930896,0.620366,0.815359

In [ ]:
df_matrix1.sort_values(by='col1', ascending=True)

,col1,col2,col3,col4,col5,col6,col7
2023-06-01,0.053088,0.581713,0.701319,0.935160,0.295908,0.968333,0.628520
2023-05-31,0.104276,0.853420,0.341653,0.275384,0.034788,0.769765,0.849421
2023-05-27,0.172614,0.294866,0.692154,0.337070,0.279661,0.044203,0.579879
2023-05-28,0.505200,0.258107,0.344459,0.297809,0.100074,0.566608,0.709941
2023-05-29,0.527226,0.945256,0.848665,0.420341,0.629450,0.981475,0.011028
2023-06-02,0.711387,0.788294,0.918252,0.006772,0.577184,0.265871,0.570120
2023-05-30,0.948951,0.406895,0.032811,0.309866,0.930896,0.620366,0.815359

In [ ]:
df_matrix1.sort_values(by='col1', ascending=False)

,col1,col2,col3,col4,col5,col6,col7
2023-05-30,0.948951,0.406895,0.032811,0.309866,0.930896,0.620366,0.815359
2023-06-02,0.711387,0.788294,0.918252,0.006772,0.577184,0.265871,0.570120
2023-05-29,0.527226,0.945256,0.848665,0.420341,0.629450,0.981475,0.011028
2023-05-28,0.505200,0.258107,0.344459,0.297809,0.100074,0.566608,0.709941
2023-05-27,0.172614,0.294866,0.692154,0.337070,0.279661,0.044203,0.579879
2023-05-31,0.104276,0.853420,0.341653,0.275384,0.034788,0.769765,0.849421
2023-06-01,0.053088,0.581713,0.701319,0.935160,0.295908,0.968333,0.628520

In [ ]:
df_dict1

     A
a  1.0
b  2.0
c  3.0
d  NaN
e  NaN

In [ ]:
del df_dict1['B']

KeyError: ignored

In [ ]:
df_dict1

In [ ]:
df_dict2

In [ ]:
df_dict2 = df_dict2

In [ ]:
df_dict2 = df_dict2.drop(['fig'])
df_dict2

In [ ]:
df_dict2 = df_dict2.drop(['grapes'], axis=0)
df_dict2

In [ ]:
df_dict2 = df_dict2.drop(['cherries'], axis=0, inplace=False)
df_dict2

In [ ]:
df_matrix1

,col1,col2,col3,col4,col5,col6,col7
2023-05-27,0.172614,0.294866,0.692154,0.337070,0.279661,0.044203,0.579879
2023-05-28,0.505200,0.258107,0.344459,0.297809,0.100074,0.566608,0.709941
2023-05-29,0.527226,0.945256,0.848665,0.420341,0.629450,0.981475,0.011028
2023-05-30,0.948951,0.406895,0.032811,0.309866,0.930896,0.620366,0.815359
2023-05-31,0.104276,0.853420,0.341653,0.275384,0.034788,0.769765,0.849421
2023-06-01,0.053088,0.581713,0.701319,0.935160,0.295908,0.968333,0.628520
2023-06-02,0.711387,0.788294,0.918252,0.006772,0.577184,0.265871,0.570120

In [ ]:
df_matrix1.loc[:,:]

,col1,col2,col3,col4,col5,col6,col7
2023-05-27,0.172614,0.294866,0.692154,0.337070,0.279661,0.044203,0.579879
2023-05-28,0.505200,0.258107,0.344459,0.297809,0.100074,0.566608,0.709941
2023-05-29,0.527226,0.945256,0.848665,0.420341,0.629450,0.981475,0.011028
2023-05-30,0.948951,0.406895,0.032811,0.309866,0.930896,0.620366,0.815359
2023-05-31,0.104276,0.853420,0.341653,0.275384,0.034788,0.769765,0.849421
2023-06-01,0.053088,0.581713,0.701319,0.935160,0.295908,0.968333,0.628520
2023-06-02,0.711387,0.788294,0.918252,0.006772,0.577184,0.265871,0.570120

In [ ]:
df_matrix1.loc['2023-05-30','col3':'col4']

col3    0.032811
col4    0.309866
Name: 2023-05-30 00:00:00, dtype: float64

In [ ]:
df_matrix1.loc['2023-05-29':'2023-05-31',:]

,col1,col2,col3,col4,col5,col6,col7
2023-05-29,0.527226,0.945256,0.848665,0.420341,0.629450,0.981475,0.011028
2023-05-30,0.948951,0.406895,0.032811,0.309866,0.930896,0.620366,0.815359
2023-05-31,0.104276,0.853420,0.341653,0.275384,0.034788,0.769765,0.849421

In [ ]:
df_matrix1.loc['2023-05-29':'2023-05-31','col3':'col5']

                col3      col4      col5
2023-05-29  0.848665  0.420341  0.629450
2023-05-30  0.032811  0.309866  0.930896
2023-05-31  0.341653  0.275384  0.034788

In [ ]:
df_matrix1.loc[:,:]

,col1,col2,col3,col4,col5,col6,col7
2023-05-27,0.172614,0.294866,0.692154,0.337070,0.279661,0.044203,0.579879
2023-05-28,0.505200,0.258107,0.344459,0.297809,0.100074,0.566608,0.709941
2023-05-29,0.527226,0.945256,0.848665,0.420341,0.629450,0.981475,0.011028
2023-05-30,0.948951,0.406895,0.032811,0.309866,0.930896,0.620366,0.815359
2023-05-31,0.104276,0.853420,0.341653,0.275384,0.034788,0.769765,0.849421
2023-06-01,0.053088,0.581713,0.701319,0.935160,0.295908,0.968333,0.628520
2023-06-02,0.711387,0.788294,0.918252,0.006772,0.577184,0.265871,0.570120

In [ ]:
df_matrix1.loc[:, :]

,col1,col2,col3,col4,col5,col6,col7
2023-05-27,0.172614,0.294866,0.692154,0.337070,0.279661,0.044203,0.579879
2023-05-28,0.505200,0.258107,0.344459,0.297809,0.100074,0.566608,0.709941
2023-05-29,0.527226,0.945256,0.848665,0.420341,0.629450,0.981475,0.011028
2023-05-30,0.948951,0.406895,0.032811,0.309866,0.930896,0.620366,0.815359
2023-05-31,0.104276,0.853420,0.341653,0.275384,0.034788,0.769765,0.849421
2023-06-01,0.053088,0.581713,0.701319,0.935160,0.295908,0.968333,0.628520
2023-06-02,0.711387,0.788294,0.918252,0.006772,0.577184,0.265871,0.570120

In [ ]:
df_matrix1.iloc[:, :]

,col1,col2,col3,col4,col5,col6,col7
2023-05-27,0.172614,0.294866,0.692154,0.337070,0.279661,0.044203,0.579879
2023-05-28,0.505200,0.258107,0.344459,0.297809,0.100074,0.566608,0.709941
2023-05-29,0.527226,0.945256,0.848665,0.420341,0.629450,0.981475,0.011028
2023-05-30,0.948951,0.406895,0.032811,0.309866,0.930896,0.620366,0.815359
2023-05-31,0.104276,0.853420,0.341653,0.275384,0.034788,0.769765,0.849421
2023-06-01,0.053088,0.581713,0.701319,0.935160,0.295908,0.968333,0.628520
2023-06-02,0.711387,0.788294,0.918252,0.006772,0.577184,0.265871,0.570120

In [ ]:
df_matrix1.loc['2023-05-27':'2023-06-01', :]

,col1,col2,col3,col4,col5,col6,col7
2023-05-27,0.172614,0.294866,0.692154,0.337070,0.279661,0.044203,0.579879
2023-05-28,0.505200,0.258107,0.344459,0.297809,0.100074,0.566608,0.709941
2023-05-29,0.527226,0.945256,0.848665,0.420341,0.629450,0.981475,0.011028
2023-05-30,0.948951,0.406895,0.032811,0.309866,0.930896,0.620366,0.815359
2023-05-31,0.104276,0.853420,0.341653,0.275384,0.034788,0.769765,0.849421
2023-06-01,0.053088,0.581713,0.701319,0.935160,0.295908,0.968333,0.628520

In [ ]:
df_matrix1.iloc[0:6, :]

,col1,col2,col3,col4,col5,col6,col7
2023-05-27,0.172614,0.294866,0.692154,0.337070,0.279661,0.044203,0.579879
2023-05-28,0.505200,0.258107,0.344459,0.297809,0.100074,0.566608,0.709941
2023-05-29,0.527226,0.945256,0.848665,0.420341,0.629450,0.981475,0.011028
2023-05-30,0.948951,0.406895,0.032811,0.309866,0.930896,0.620366,0.815359
2023-05-31,0.104276,0.853420,0.341653,0.275384,0.034788,0.769765,0.849421
2023-06-01,0.053088,0.581713,0.701319,0.935160,0.295908,0.968333,0.628520

In [ ]:
df_matrix1.loc['2023-05-28': '2023-05-31', 'col2': 'col6']

                col2      col3      col4      col5      col6
2023-05-28  0.258107  0.344459  0.297809  0.100074  0.566608
2023-05-29  0.945256  0.848665  0.420341  0.629450  0.981475
2023-05-30  0.406895  0.032811  0.309866  0.930896  0.620366
2023-05-31  0.853420  0.341653  0.275384  0.034788  0.769765

In [ ]:
df_matrix1.iloc[1:5,1:6]

                col2      col3      col4      col5      col6
2023-05-28  0.258107  0.344459  0.297809  0.100074  0.566608
2023-05-29  0.945256  0.848665  0.420341  0.629450  0.981475
2023-05-30  0.406895  0.032811  0.309866  0.930896  0.620366
2023-05-31  0.853420  0.341653  0.275384  0.034788  0.769765

In [ ]:
df_matrix1.loc[:, 'col3':'col6']

                col3      col4      col5      col6
2023-05-27  0.692154  0.337070  0.279661  0.044203
2023-05-28  0.344459  0.297809  0.100074  0.566608
2023-05-29  0.848665  0.420341  0.629450  0.981475
2023-05-30  0.032811  0.309866  0.930896  0.620366
2023-05-31  0.341653  0.275384  0.034788  0.769765
2023-06-01  0.701319  0.935160  0.295908  0.968333
2023-06-02  0.918252  0.006772  0.577184  0.265871

In [ ]:
df_matrix1.iloc[:, 2:6]

                col3      col4      col5      col6
2023-05-27  0.692154  0.337070  0.279661  0.044203
2023-05-28  0.344459  0.297809  0.100074  0.566608
2023-05-29  0.848665  0.420341  0.629450  0.981475
2023-05-30  0.032811  0.309866  0.930896  0.620366
2023-05-31  0.341653  0.275384  0.034788  0.769765
2023-06-01  0.701319  0.935160  0.295908  0.968333
2023-06-02  0.918252  0.006772  0.577184  0.265871

In [ ]:
import pandas as pd

In [ ]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'

In [ ]:
df_chipotle = pd.read_csv(url, sep='\t')
df_chipotle

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [ ]:
# Filtering and Sorting

In [ ]:
df_chipotle = pd.read_csv(url, sep='\t')
df_chipotle

for i in df_chipotle.item_price:
  print(i, float(i[1:-1]))
  print(df_chipotle.item_price)
  df_chipotle.item_price = float(i[1:-1])

Streaming output truncated to the last 5000 lines.
4       8.5
       ...
4617    8.5
4618    8.5
4619    8.5
4620    8.5
4621    8.5
Name: item_price, Length: 4622, dtype: float64
$11.25  11.25
0       8.5
1       8.5
2       8.5
3       8.5
4       8.5
       ...
4617    8.5
4618    8.5
4619    8.5
4620    8.5
4621    8.5
Name: item_price, Length: 4622, dtype: float64
$11.89  11.89
0       11.25
1       11.25
2       11.25
3       11.25
4       11.25
        ...
4617    11.25
4618    11.25
4619    11.25
4620    11.25
4621    11.25
Name: item_price, Length: 4622, dtype: float64
$1.25  1.25
0       11.89
1       11.89
2       11.89
3       11.89
4       11.89
        ...
4617    11.89
4618    11.89
4619    11.89
4620    11.89
4621    11.89
Name: item_price, Length: 4622, dtype: float64
$9.39  9.39
0       1.25
1       1.25
2       1.25
3       1.25
4       1.25
        ...
4617    1.25
4618    1.25
4619    1.25
4620    1.25
4621    1.25
Name: item_price, Length: 4622, dtype: float64
$4.45  4.45
0       9.39
1       9.39
2       9.39
3       9.39
4       9.39
        ...
4617    9.39
4618    9.39
4619    9.39
4620    9.39
4621    9.39
Name: item_price, Length: 4622, dtype: float64
$8.75  8.75
0       4.45
1       4.45
2       4.45
3       4.45
4       4.45
        ...
4617    4.45
4618    4.45
4619    4.45
4620    4.45
4621    4.45
Name: item_price, Length: 4622, dtype: float64
$2.15  2.15
0       8.75
1       8.75
2       8.75
3       8.75
4       8.75
        ...
4617    8.75
4618    8.75
4619    8.75
4620    8.75
4621    8.75
Name: item_price, Length: 4622, dtype: float64
$1.50  1.5
0       2.15
1       2.15
2       2.15
3       2.15
4       2.15
        ...
4617    2.15
4618    2.15
4619    2.15
4620    2.15
4621    2.15
Name: item_price, Length: 4622, dtype: float64
$11.75  11.75
0       1.5
1       1.5
2       1.5
3       1.5
4       1.5
       ...
4617    1.5
4618    1.5
4619    1.5
4620    1.5
4621    1.5
Name: item_price, Length: 4622, dtype: float64
$8.75  8.75
0       11.75
1       11.75
2       11.75
3       11.75
4       11.75
        ...
4617    11.75
4618    11.75
4619    11.75
4620    11.75
4621    11.75
Name: item_price, Length: 4622, dtype: float64
$9.25  9.25
0       8.75
1       8.75
2       8.75
3       8.75
4       8.75
        ...
4617    8.75
4618    8.75
4619    8.75
4620    8.75
4621    8.75
Name: item_price, Length: 4622, dtype: float64
$9.25  9.25
0       9.25
1       9.25
2       9.25
3       9.25
4       9.25
        ...
4617    9.25
4618    9.25
4619    9.25
4620    9.25
4621    9.25
Name: item_price, Length: 4622, dtype: float64
$4.45  4.45
0       9.25
1       9.25
2       9.25
3       9.25
4       9.25
        ...
4617    9.25
4618    9.25
4619    9.25
4620    9.25
4621    9.25
Name: item_price, Length: 4622, dtype: float64
$1.25  1.25
0       4.45
1       4.45
2       4.45
3       4.45
4       4.45
        ...
4617    4.45
4618    4.45
4619    4.45
4620    4.45
4621    4.45
Name: item_price, Length: 4622, dtype: float64
$11.25  11.25
0       1.25
1       1.25
2       1.25
3       1.25
4       1.25
        ...
4617    1.25
4618    1.25
4619    1.25
4620    1.25
4621    1.25
Name: item_price, Length: 4622, dtype: float64
$9.25  9.25
0       11.25
1       11.25
2       11.25
3       11.25
4       11.25
        ...
4617    11.25
4618    11.25
4619    11.25
4620    11.25
4621    11.25
Name: item_price, Length: 4622, dtype: float64
$2.95  2.95
0       9.25
1       9.25
2       9.25
3       9.25
4       9.25
        ...
4617    9.25
4618    9.25
4619    9.25
4620    9.25
4621    9.25
Name: item_price, Length: 4622, dtype: float64
$8.75  8.75
0       2.95
1       2.95
2       2.95
3       2.95
4       2.95
        ...
4617    2.95
4618    2.95
4619    2.95
4620    2.95
4621    2.95
Name: item_price, Length: 4622, dtype: float64
$8.75  8.75
0       8.75
1       8.75
2       8.75
3       8.75
4       8.75
        ...
4617    8.75
4618    8.75
4619    8.75
4620    8.75
4621    8.75
Name: item_price, Length: 4622, dtype: float64
$2.15  2.15
0       8.75
1       8.75
2       8.75
3       8.75
4       8.75
        ...
4617    8.75
4618    8.75
4619    8.75
4620    8.75
4621    8.75
Name: item_price, Length: 4622, dtype: float64
$8.75  8.75
0       2.15
1       2.15
2       2.15
3       2.15
4       2.15
        ...
4617    2.15
4618    2.15
4619    2.15
4620    2.15
4621    2.15
Name: item_price, Length: 4622, dtype: float64
$11.25  11.25
0       8.75
1       8.75
2       8.75
3       8.75
4       8.75
        ...
4617    8.75
4618    8.75
4619    8.75
4620    8.75
4621    8.75
Name: item_price, Length: 4622, dtype: float64
$11.25  11.25
0       11.25
1       11.25
2       11.25
3       11.25
4       11.25
        ...
4617    11.25
4618    11.25
4619    11.25
4620    11.25
4621    11.25
Name: item_price, Length: 4622, dtype: float64
$11.25  11.25
0       11.25
1       11.25
2       11.25
3       11.25
4       11.25
        ...
4617    11.25
4618    11.25
4619    11.25
4620    11.25
4621    11.25
Name: item_price, Length: 4622, dtype: float64
$11.75  11.75
0       11.25
1       11.25
2       11.25
3       11.25
4       11.25
        ...
4617    11.25
4618    11.25
4619    11.25
4620    11.25
4621    11.25
Name: item_price, Length: 4622, dtype: float64
$11.25  11.25
0       11.75
1       11.75
2       11.75
3       11.75
4       11.75
        ...
4617    11.75
4618    11.75
4619    11.75
4620    11.75
4621    11.75
Name: item_price, Length: 4622, dtype: float64
$2.15  2.15
0       11.25
1       11.25
2       11.25
3       11.25
4       11.25
        ...
4617    11.25
4618    11.25
4619    11.25
4620    11.25
4621    11.25
Name: item_price, Length: 4622, dtype: float64
$11.25  11.25
0       2.15
1       2.15
2       2.15
3       2.15
4       2.15
        ...
4617    2.15
4618    2.15
4619    2.15
4620    2.15
4621    2.15
Name: item_price, Length: 4622, dtype: float64
$2.15  2.15
0       11.25
1       11.25
2       11.25
3       11.25
4       11.25
        ...
4617    11.25
4618    11.25
4619    11.25
4620    11.25
4621    11.25
Name: item_price, Length: 4622, dtype: float64
$8.99  8.99
0       2.15
1       2.15
2       2.15
3       2.15
4       2.15
        ...
4617    2.15
4618    2.15
4619    2.15
4620    2.15
4621    2.15
Name: item_price, Length: 4622, dtype: float64
$8.99  8.99
0       8.99
1       8.99
2       8.99
3       8.99
4       8.99
        ...
4617    8.99
4618    8.99
4619    8.99
4620    8.99
4621    8.99
Name: item_price, Length: 4622, dtype: float64
$8.75  8.75
0       8.99
1       8.99
2       8.99
3       8.99
4       8.99
        ...
4617    8.99
4618    8.99
4619    8.99
4620    8.99
4621    8.99
Name: item_price, Length: 4622, dtype: float64
$9.25  9.25
0       8.75
1       8.75
2       8.75
3       8.75
4       8.75
        ...
4617    8.75
4618    8.75
4619    8.75
4620    8.75
4621    8.75
Name: item_price, Length: 4622, dtype: float64
$9.25  9.25
0       9.25
1       9.25
2       9.25
3       9.25
4       9.25
        ...
4617    9.25
4618    9.25
4619    9.25
4620    9.25
4621    9.25
Name: item_price, Length: 4622, dtype: float64
$11.25  11.25
0       9.25
1       9.25
2       9.25
3       9.25
4       9.25
        ...
4617    9.25
4618    9.25
4619    9.25
4620    9.25
4621    9.25
Name: item_price, Length: 4622, dtype: float64
$8.75  8.75
0       11.25
1       11.25
2       11.25
3       11.25
4       11.25
        ...
4617    11.25
4618    11.25
4619    11.25
4620    11.25
4621    11.25
Name: item_price, Length: 4622, dtype: float64
$4.45  4.45
0       8.75
1       8.75
2       8.75
3       8.75
4       8.75
        ...
4617    8.75
4618    8.75
4619    8.75
4620    8.75
4621    8.75
Name: item_price, Length: 4622, dtype: float64
$8.75  8.75
0       4.45
1       4.45
2       4.45
3       4.45
4       4.45
        ...
4617    4.45
4618    4.45
4619    4.45
4620    4.45
4621    4.45
Name: item_price, Length: 4622, dtype: float64
$1.25  1.25
0       8.75
1       8.75
2       8.75
3       8.75
4       8.75
        ...
4617    8.75
4618    8.75
4619    8.75
4620    8.75
4621    8.75
Name: item_price, Length: 4622, dtype: float64
$4.45  4.45
0       1.25
1       1.25
2       1.25
3       1.25
4       1.25
        ...
4617    1.25
4618    1.25
4619    1.25
4620    1.25
4621    1.25
Name: item_price, Length: 4622, dtype: float64
$11.25  11.25
0       4.45
1       4.45
2       4.45
3       4.45
4       4.45
        ...
4617    4.45
4618    4.45
4619    4.45
4620    4.45
4621    4.45
Name: item_price, Length: 4622, dtype: float64
$1.25  1.25
0       11.25
1       11.25
2       11.25
3       11.25
4       11.25
        ...
4617    11.25
4618    11.25
4619    11.25
4620    11.25
4621    11.25
Name: item_price, Length: 4622, dtype: float64
$8.75  8.75
0       1.25
1       1.25
2       1.25
3       1.25
4       1.25
        ...
4617    1.25
4618    1.25
4619    1.25
4620    1.25
4621    1.25
Name: item_price, Length: 4622, dtype: float64
$8.75  8.75
0       8.75
1       8.75
2       8.75
3       8.75
4       8.75
        ...
4617    8.75
4618    8.75
4619    8.75
4620    8.75
4621    8.75
Name: item_price, Length: 4622, dtype: float64
$11.25  11.25
0       8.75
1       8.75
2       8.75
3       8.75
4       8.75
        ...
4617    8.75
4618    8.75
4619    8.75
4620    8.75
4621    8.75
Name: item_price, Length: 4622, dtype: float64
$8.75  8.75
0       11.25
1       11.25
2       11.25
3       11.25
4       11.25
        ...
4617    11.25
4618    11.25
4619    11.25
4620    11.25
4621    11.25
Name: item_price, Length: 4622, dtype: float64
$1.25  1.25
0       8.75
1       8.75
2       8.75
3       8.75
4       8.75
        ...
4617    8.75
4618    8.75
4619    8.75
4620    8.75
4621    8.75
Name: item_price, Length: 4622, dtype: float64
$1.25  1.25
0       1.25
1       1.25
2       1.25
3       1.25
4       1.25
        ...
4617    1.25
4618    1.25
4619    1.25
4620    1.25
4621    1.25
Name: item_price, Length: 4622, dtype: float64
$1.25  1.25
0       1.25
1       1.25
2       1.25
3       1.25
4       1.25
        ...
4617    1.25
4618    1.25
4619    1.25
4620    1.25
4621    1.25
Name: item_price, Length: 4622, dtype: float64
$9.25  9.25
0       1.25
1       1.25
2       1.25
3       1.25
4       1.25
        ...
4617    1.25
4618    1.25
4619    1.25
4620    1.25
4621    1.25
Name: item_price, Length: 4622, dtype: float64
$11.75  11.75
0       9.25
1       9.25
2       9.25
3       9.25
4       9.25
        ...
4617    9.25
4618    9.25
4619    9.25
4620    9.25
4621    9.25
Name: item_price, Length: 4622, dtype: float64
$2.15  2.15
0       11.75
1       11.75
2       11.75
3       11.75
4       11.75
        ...
4617    11.75
4618    11.75
4619    11.75
4620    11.75
4621    11.75
Name: item_price, Length: 4622, dtype: float64
$8.75  8.75
0       2.15
1       2.15
2       2.15
3       2.15
4       2.15
        ...
4617    2.15
4618    2.15
4619    2.15
4620    2.15
4621    2.15
Name: item_price, Length: 4622, dtype: float64
$4.45  4.45
0       8.75
1       8.75
2       8.75
3       8.75
4       8.75
        ...
4617    8.75
4618    8.75
4619    8.75
4620    8.75
4621    8.75
Name: item_price, Length: 4622, dtype: float64
$8.75  8.75
0       4.45
1       4.45
2       4.45
3       4.45
4       4.45
        ...
4617    4.45
4618    4.45
4619    4.45
4620    4.45
4621    4.45
Name: item_price, Length: 4622, dtype: float64
$4.45  4.45
0       8.75
1       8.75
2       8.75
3       8.75
4       8.75
        ...
4617    8.75
4618    8.75
4619    8.75
4620    8.75
4621    8.75
Name: item_price, Length: 4622, dtype: float64
$11.25  11.25
0       4.45
1       4.45
2       4.45
3       4.45
4       4.45
        ...
4617    4.45
4618    4.45
4619    4.45
4620    4.45
4621    4.45
Name: item_price, Length: 4622, dtype: float64
$9.25  9.25
0       11.25
1       11.25
2       11.25
3       11.25
4       11.25
        ...
4617    11.25
4618    11.25
4619    11.25
4620    11.25
4621    11.25
Name: item_price, Length: 4622, dtype: float64
$8.75  8.75
0       9.25
1       9.25
2       9.25
3       9.25
4       9.25
        ...
4617    9.25
4618    9.25
4619    9.25
4620    9.25
4621    9.25
Name: item_price, Length: 4622, dtype: float64
$9.25  9.25
0       8.75
1       8.75
2       8.75
3       8.75
4       8.75
        ...
4617    8.75
4618    8.75
4619    8.75
4620    8.75
4621    8.75
Name: item_price, Length: 4622, dtype: float64
$4.45  4.45
0       9.25
1       9.25
2       9.25
3       9.25
4       9.25
        ...
4617    9.25
4618    9.25
4619    9.25
4620    9.25
4621    9.25
Name: item_price, Length: 4622, dtype: float64
$11.75  11.75
0       4.45
1       4.45
2       4.45
3       4.45
4       4.45
        ...
4617    4.45
4618    4.45
4619    4.45
4620    4.45
4621    4.45
Name: item_price, Length: 4622, dtype: float64
$4.45  4.45
0       11.75
1       11.75
2       11.75
3       11.75
4       11.75
        ...
4617    11.75
4618    11.75
4619    11.75
4620    11.75
4621    11.75
Name: item_price, Length: 4622, dtype: float64
$1.25  1.25
0       4.45
1       4.45
2       4.45
3       4.45
4       4.45
        ...
4617    4.45
4618    4.45
4619    4.45
4620    4.45
4621    4.45
Name: item_price, Length: 4622, dtype: float64
$4.45  4.45
0       1.25
1       1.25
2       1.25
3       1.25
4       1.25
        ...
4617    1.25
4618    1.25
4619    1.25
4620    1.25
4621    1.25
Name: item_price, Length: 4622, dtype: float64
$11.75  11.75
0       4.45
1       4.45
2       4.45
3       4.45
4       4.45
        ...
4617    4.45
4618    4.45
4619    4.45
4620    4.45
4621    4.45
Name: item_price, Length: 4622, dtype: float64
$9.25  9.25
0       11.75
1       11.75
2       11.75
3       11.75
4       11.75
        ...
4617    11.75
4618    11.75
4619    11.75
4620    11.75
4621    11.75
Name: item_price, Length: 4622, dtype: float64
$11.25  11.25
0       9.25
1       9.25
2       9.25
3       9.25
4       9.25
        ...
4617    9.25
4618    9.25
4619    9.25
4620    9.25
4621    9.25
Name: item_price, Length: 4622, dtype: float64
$2.15  2.15
0       11.25
1       11.25
2       11.25
3       11.25
4       11.25
        ...
4617    11.25
4618    11.25
4619    11.25
4620    11.25
4621    11.25
Name: item_price, Length: 4622, dtype: float64
$23.50  23.5
0       2.15
1       2.15
2       2.15
3       2.15
4       2.15
        ...
4617    2.15
4618    2.15
4619    2.15
4620    2.15
4621    2.15
Name: item_price, Length: 4622, dtype: float64
$9.25  9.25
0       23.5
1       23.5
2       23.5
3       23.5
4       23.5
        ...
4617    23.5
4618    23.5
4619    23.5
4620    23.5
4621    23.5
Name: item_price, Length: 4622, dtype: float64
$2.15  2.15
0       9.25
1       9.25
2       9.25
3       9.25
4       9.25
        ...
4617    9.25
4618    9.25
4619    9.25
4620    9.25
4621    9.25
Name: item_price, Length: 4622, dtype: float64
$18.50  18.5
0       2.15
1       2.15
2       2.15
3       2.15
4       2.15
        ...
4617    2.15
4618    2.15
4619    2.15
4620    2.15
4621    2.15
Name: item_price, Length: 4622, dtype: float64
$8.75  8.75
0       18.5
1       18.5
2       18.5
3       18.5
4       18.5
        ...
4617    18.5
4618    18.5
4619    18.5
4620    18.5
4621    18.5
Name: item_price, Length: 4622, dtype: float64
$5.90  5.9
0       8.75
1       8.75
2       8.75
3       8.75
4       8.75
        ...
4617    8.75
4618    8.75
4619    8.75
4620    8.75
4621    8.75
Name: item_price, Length: 4622, dtype: float64
$11.89  11.89
0       5.9
1       5.9
2       5.9
3       5.9
4       5.9
       ...
4617    5.9
4618    5.9
4619    5.9
4620    5.9
4621    5.9
Name: item_price, Length: 4622, dtype: float64
$4.45  4.45
0       11.89
1       11.89
2       11.89
3       11.89
4       11.89
        ...
4617    11.89
4618    11.89
4619    11.89
4620    11.89
4621    11.89
Name: item_price, Length: 4622, dtype: float64
$8.75  8.75
0       4.45
1       4.45
2       4.45
3       4.45
4       4.45
        ...
4617    4.45
4618    4.45
4619    4.45
4620    4.45
4621    4.45
Name: item_price, Length: 4622, dtype: float64
$4.45  4.45
0       8.75
1       8.75
2       8.75
3       8.75
4       8.75
        ...
4617    8.75
4618    8.75
4619    8.75
4620    8.75
4621    8.75
Name: item_price, Length: 4622, dtype: float64
$9.25  9.25
0       4.45
1       4.45
2       4.45
3       4.45
4       4.45
        ...
4617    4.45
4618    4.45
4619    4.45
4620    4.45
4621    4.45
Name: item_price, Length: 4622, dtype: float64
$2.95  2.95
0       9.25
1       9.25
2       9.25
3       9.25
4       9.25
        ...
4617    9.25
4618    9.25
4619    9.25
4620    9.25
4621    9.25
Name: item_price, Length: 4622, dtype: float64
$11.25  11.25
0       2.95
1       2.95
2       2.95
3       2.95
4       2.95
        ...
4617    2.95
4618    2.95
4619    2.95
4620    2.95
4621    2.95
Name: item_price, Length: 4622, dtype: float64
$2.95  2.95
0       11.25
1       11.25
2       11.25
3       11.25
4       11.25
        ...
4617    11.25
4618    11.25
4619    11.25
4620    11.25
4621    11.25
Name: item_price, Length: 4622, dtype: float64
$11.25  11.25
0       2.95
1       2.95
2       2.95
3       2.95
4       2.95
        ...
4617    2.95
4618    2.95
4619    2.95
4620    2.95
4621    2.95
Name: item_price, Length: 4622, dtype: float64
$11.25  11.25
0       11.25
1       11.25
2       11.25
3       11.25
4       11.25
        ...
4617    11.25
4618    11.25
4619    11.25
4620    11.25
4621    11.25
Name: item_price, Length: 4622, dtype: float64
$11.25  11.25
0       11.25
1       11.25
2       11.25
3       11.25
4       11.25
        ...
4617    11.25
4618    11.25
4619    11.25
4620    11.25
4621    11.25
Name: item_price, Length: 4622, dtype: float64
$2.95  2.95
0       11.25
1       11.25
2       11.25
3       11.25
4       11.25
        ...
4617    11.25
4618    11.25
4619    11.25
4620    11.25
4621    11.25
Name: item_price, Length: 4622, dtype: float64
$11.75  11.75
0       2.95
1       2.95
2       2.95
3       2.95
4       2.95
        ...
4617    2.95
4618    2.95
4619    2.95
4620    2.95
4621    2.95
Name: item_price, Length: 4622, dtype: float64
$9.25  9.25
0       11.75
1       11.75
2       11.75
3       11.75
4       11.75
        ...
4617    11.75
4618    11.75
4619    11.75
4620    11.75
4621    11.75
Name: item_price, Length: 4622, dtype: float64
$9.25  9.25
0       9.25
1       9.25
2       9.25
3       9.25
4       9.25
        ...
4617    9.25
4618    9.25
4619    9.25
4620    9.25
4621    9.25
Name: item_price, Length: 4622, dtype: float64
$2.95  2.95
0       9.25
1       9.25
2       9.25
3       9.25
4       9.25
        ...
4617    9.25
4618    9.25
4619    9.25
4620    9.25
4621    9.25
Name: item_price, Length: 4622, dtype: float64
$11.25  11.25
0       2.95
1       2.95
2       2.95
3       2.95
4       2.95
        ...
4617    2.95
4618    2.95
4619    2.95
4620    2.95
4621    2.95
Name: item_price, Length: 4622, dtype: float64
$2.15  2.15
0       11.25
1       11.25
2       11.25
3       11.25
4       11.25
        ...
4617    11.25
4618    11.25
4619    11.25
4620    11.25
4621    11.25
Name: item_price, Length: 4622, dtype: float64
$9.25  9.25
0       2.15
1       2.15
2       2.15
3       2.15
4       2.15
        ...
4617    2.15
4618    2.15
4619    2.15
4620    2.15
4621    2.15
Name: item_price, Length: 4622, dtype: float64
$8.90  8.9
0       9.25
1       9.25
2       9.25
3       9.25
4       9.25
        ...
4617    9.25
4618    9.25
4619    9.25
4620    9.25
4621    9.25
Name: item_price, Length: 4622, dtype: float64
$8.75  8.75
0       8.9
1       8.9
2       8.9
3       8.9
4       8.9
       ...
4617    8.9
4618    8.9
4619    8.9
4620    8.9
4621    8.9
Name: item_price, Length: 4622, dtype: float64
$11.25  11.25
0       8.75
1       8.75
2       8.75
3       8.75
4       8.75
        ...
4617    8.75
4618    8.75
4619    8.75
4620    8.75
4621    8.75
Name: item_price, Length: 4622, dtype: float64
$11.25  11.25
0       11.25
1       11.25
2       11.25

In [ ]:
df_chipotle = pd.read_csv(url, sep='\t')
df_chipotle


# clean the item_price column and transform it in a float
prices = [float(value[1 : -1]) for value in df_chipotle.item_price]
print(prices)
# reassign the column with the cleaned prices
df_chipotle.item_price = prices 

# make the comparison
chipo10 = df_chipotle[df_chipotle['item_price'] > 10.00]
chipo10.head()

len(chipo10)
print(df_chipotle)

[2.39, 3.39, 3.39, 2.39, 16.98, 10.98, 1.69, 11.75, 9.25, 9.25, 4.45, 8.75, 8.75, 11.25, 4.45, 2.39, 8.49, 8.49, 2.18, 8.75, 4.45, 8.99, 3.39, 10.98, 3.39, 2.39, 8.49, 8.99, 1.09, 8.49, 2.39, 8.99, 1.69, 8.99, 1.09, 8.75, 8.75, 4.45, 2.95, 11.75, 2.15, 4.45, 11.25, 11.75, 8.75, 10.98, 8.99, 3.39, 8.99, 3.99, 8.99, 2.18, 10.98, 1.09, 8.99, 2.39, 9.25, 11.25, 11.75, 2.15, 4.45, 9.25, 11.25, 8.75, 8.99, 8.99, 3.39, 8.99, 10.98, 8.99, 1.69, 8.99, 3.99, 8.75, 4.45, 8.75, 8.75, 2.15, 8.75, 11.25, 2.15, 9.25, 8.75, 8.75, 9.25, 8.49, 8.99, 1.09, 9.25, 2.95, 11.75, 11.75, 9.25, 11.75, 4.45, 9.25, 4.45, 11.75, 8.75, 8.75, 4.45, 8.99, 8.99, 3.99, 8.49, 3.39, 8.99, 1.09, 9.25, 4.45, 8.75, 2.95, 4.45, 2.39, 8.49, 8.99, 8.49, 1.09, 8.99, 3.99, 8.75, 9.25, 4.45, 11.25, 4.45, 8.99, 1.09, 9.25, 2.95, 4.45, 11.75, 4.45, 8.49, 2.39, 10.98, 22.5, 11.75, 4.45, 11.25, 4.45, 11.25, 4.45, 11.25, 11.25, 11.75, 9.25, 4.45, 11.48, 17.98, 1.69, 17.5, 4.45, 8.49, 2.39, 17.5, 4.45, 4.45, 11.25, 11.75, 10.98, 8.49, 10.98, 2.18, 11.48, 8.49, 2.39, 4.45, 11.25, 11.75, 8.75, 8.49, 2.18, 8.49, 3.39, 8.49, 8.99, 10.98, 11.48, 8.49, 1.09, 1.09, 9.25, 8.75, 2.95, 9.25, 4.45, 11.25, 11.48, 8.49, 8.49, 8.99, 2.39, 11.25, 8.75, 2.95, 1.09, 8.99, 8.49, 2.39, 10.98, 1.09, 3.99, 11.25, 8.75, 8.49, 3.39, 8.75, 9.25, 2.15, 11.25, 11.25, 11.25, 4.45, 22.5, 4.45, 11.75, 8.75, 17.5, 8.75, 9.25, 8.75, 2.15, 9.25, 4.3, 8.75, 11.25, 2.15, 8.99, 1.09, 8.99, 3.99, 8.75, 2.95, 2.95, 11.75, 5.9, 9.25, 9.25, 11.75, 9.25, 2.95, 17.5, 8.75, 9.25, 10.98, 8.99, 1.09, 1.09, 1.09, 8.99, 10.98, 1.09, 8.75, 8.75, 9.25, 9.25, 8.75, 8.75, 8.99, 8.99, 8.99, 1.09, 11.75, 1.25, 8.99, 2.39, 9.25, 2.95, 8.99, 3.99, 8.49, 2.39, 8.49, 8.49, 8.49, 1.69, 8.49, 3.99, 8.99, 1.69, 1.09, 23.78, 17.5, 2.15, 8.75, 9.25, 9.25, 8.75, 4.45, 8.75, 11.25, 11.25, 1.25, 9.25, 4.45, 11.25, 11.75, 11.75, 6.49, 8.99, 2.39, 8.49, 2.39, 11.25, 8.75, 2.15, 8.99, 1.69, 8.75, 11.25, 2.15, 4.45, 8.75, 8.49, 8.99, 17.5, 8.49, 1.09, 1.09, 8.75, 1.25, 2.15, 11.08, 8.49, 8.49, 8.99, 2.39, 8.75, 2.15, 1.5, 11.25, 2.15, 8.49, 8.49, 11.75, 9.25, 11.75, 1.25, 11.25, 8.75, 4.45, 6.49, 9.25, 2.95, 11.25, 4.45, 1.25, 1.25, 8.49, 2.39, 2.18, 8.49, 2.18, 22.16, 17.5, 8.75, 2.95, 6.49, 8.99, 3.39, 3.39, 8.99, 8.49, 11.25, 2.15, 11.25, 2.95, 11.25, 1.25, 8.99, 1.09, 8.75, 8.75, 9.25, 2.95, 11.75, 1.5, 8.99, 1.09, 11.25, 1.25, 1.25, 11.25, 11.75, 2.15, 8.99, 1.69, 11.75, 6.49, 8.75, 9.25, 11.25, 4.45, 1.25, 11.25, 4.45, 8.49, 8.99, 8.49, 8.99, 11.25, 1.25, 11.75, 1.25, 11.75, 9.25, 4.45, 11.25, 2.15, 32.94, 1.25, 11.25, 11.48, 1.69, 1.09, 17.5, 4.45, 6.49, 9.25, 8.75, 9.25, 9.25, 8.75, 8.75, 2.15, 2.95, 17.5, 10.98, 11.48, 11.48, 3.39, 8.99, 1.69, 8.99, 1.09, 10.98, 3.39, 8.99, 1.09, 9.25, 8.75, 11.25, 4.45, 2.95, 9.25, 22.2, 8.49, 8.99, 8.75, 8.75, 11.75, 8.75, 11.25, 9.25, 11.25, 11.25, 8.75, 11.25, 2.95, 1.25, 8.49, 1.69, 11.75, 11.25, 8.75, 8.75, 4.45, 8.49, 3.99, 8.49, 3.99, 11.48, 1.69, 1.09, 11.25, 1.5, 10.58, 1.69, 9.25, 11.25, 8.75, 9.25, 11.25, 11.25, 8.75, 11.75, 8.75, 8.75, 8.75, 2.15, 11.25, 11.75, 2.5, 4.45, 9.25, 4.45, 11.25, 8.49, 3.99, 9.25, 9.25, 11.25, 9.25, 11.75, 11.25, 1.25, 23.5, 1.25, 8.99, 8.49, 7.4, 7.4, 8.75, 1.25, 4.45, 8.75, 2.15, 8.75, 4.45, 7.4, 7.4, 7.4, 8.99, 3.99, 8.99, 1.69, 8.75, 8.75, 8.75, 8.75, 11.25, 11.25, 2.95, 8.75, 18.5, 8.49, 3.99, 2.95, 9.25, 9.25, 3.0, 1.25, 8.75, 9.25, 4.45, 8.75, 11.25, 4.45, 10.98, 22.16, 4.45, 8.75, 9.25, 6.49, 9.25, 11.25, 8.75, 9.25, 2.15, 9.25, 4.45, 9.25, 2.95, 9.25, 8.75, 9.25, 1.25, 1.25, 8.75, 8.75, 9.25, 4.45, 11.75, 11.75, 11.75, 9.25, 9.25, 16.98, 2.39, 3.39, 3.39, 9.25, 11.75, 11.25, 2.15, 8.75, 9.25, 4.45, 10.98, 11.25, 9.25, 22.5, 9.25, 2.95, 1.5, 11.48, 8.49, 1.69, 8.49, 8.49, 8.49, 6.78, 11.75, 4.45, 8.75, 4.45, 11.89, 9.39, 8.75, 2.95, 1.25, 9.25, 8.75, 23.78, 8.75, 9.25, 2.15, 2.15, 1.25, 8.49, 3.99, 10.98, 1.09, 8.75, 4.45, 8.75, 11.75, 2.95, 4.45, 9.25, 8.75, 8.49, 3.99, 22.5, 11.25, 1.25, 8.75, 8.75, 18.5, 6.49, 8.75, 8.75, 4.45, 8.49, 3.99, 8.99, 1.09, 8.49, 2.39, 11.48, 1.69, 2.5, 9.25, 1.5, 17.5, 2.95, 8.75, 4.45, 11.75, 8.75, 8.49, 1.69, 8.49, 3.99, 8.99, 8.99, 3.99, 8.99, 11.25, 4.45, 1.25, 3.99, 10.98, 7.4, 3.0, 7.4, 4.0, 8.49, 3.99, 9.25, 4.45, 11.25, 1.25, 11.75, 1.25, 11.25, 2.15, 11.25, 4.45, 3.75, 11.75, 8.99, 2.39, 8.75, 4.45, 1.25, 8.99, 8.49, 2.18, 8.49, 2.18, 1.09, 8.75, 2.95, 1.25, 1.5, 11.25, 9.25, 2.95, 1.25, 8.49, 3.99, 11.48, 3.99, 8.49, 11.25, 1.25, 8.99, 1.69, 11.25, 1.25, 6.49, 8.75, 9.25, 8.75, 2.95, 8.75, 11.75, 8.69, 8.69, 2.29, 3.99, 8.49, 8.75, 8.75, 1.25, 11.75, 11.25, 11.25, 11.25, 1.25, 9.25, 11.75, 6.49, 3.99, 8.49, 11.25, 2.15, 11.25, 11.89, 8.99, 1.69, 8.99, 8.99, 3.99, 8.99, 9.25, 9.25, 2.15, 7.4, 7.4, 8.75, 8.75, 9.25, 4.45, 11.25, 1.25, 11.75, 11.25, 1.25, 3.99, 8.49, 8.49, 8.49, 8.99, 8.75, 2.15, 1.25, 8.49, 1.09, 1.09, 8.75, 2.95, 1.25, 9.25, 1.25, 2.15, 11.25, 1.25, 4.45, 8.75, 2.5, 8.9, 8.75, 8.75, 8.75, 11.25, 11.25, 10.98, 3.99, 10.98, 3.99, 1.69, 8.99, 9.25, 8.75, 8.99, 1.09, 9.25, 2.95, 8.75, 9.25, 3.99, 8.49, 8.75, 8.75, 22.5, 10.98, 3.27, 3.99, 8.99, 1.09, 11.08, 8.75, 4.45, 11.08, 3.99, 8.49, 4.3, 9.25, 8.75, 11.25, 11.25, 9.25, 8.49, 8.99, 8.49, 8.75, 2.95, 4.45, 9.25, 2.95, 9.25, 8.75, 11.25, 4.45, 16.98, 8.49, 2.39, 11.25, 3.75, 9.25, 4.45, 9.25, 9.25, 4.45, 8.75, 9.25, 8.75, 9.25, 9.25, 9.25, 11.48, 8.99, 22.5, 11.75, 11.25, 1.25, 8.75, 2.15, 1.25, 11.25, 8.75, 1.25, 11.25, 1.5, 11.25, 11.25, 9.25, 6.49, 8.9, 8.75, 4.45, 11.25, 1.25, 17.5, 9.25, 8.75, 11.75, 3.0, 8.49, 8.49, 10.98, 8.99, 3.99, 8.75, 4.45, 8.99, 1.69, 11.75, 8.75, 11.25, 4.45, 11.75, 1.25, 11.75, 2.95, 8.99, 8.99, 2.18, 17.98, 8.99, 8.49, 1.69, 11.75, 11.25, 2.95, 3.75, 9.25, 11.75, 8.75, 2.15, 1.5, 8.49, 8.49, 3.39, 8.69, 3.89, 8.75, 4.45, 8.75, 11.25, 2.15, 8.75, 8.49, 1.69, 8.49, 8.49, 1.25, 8.75, 11.75, 11.75, 8.99, 1.09, 8.75, 4.45, 8.75, 2.95, 8.75, 2.15, 3.99, 8.49, 8.99, 3.99, 8.49, 1.69, 1.09, 8.99, 1.09, 9.25, 8.75, 8.99, 2.39, 1.25, 1.25, 11.25, 11.25, 9.25, 9.25, 11.25, 1.5, 3.99, 8.49, 11.25, 9.25, 11.25, 17.5, 8.75, 8.9, 8.75, 8.75, 8.99, 2.39, 11.25, 9.25, 2.15, 11.25, 1.25, 11.75, 1.25, 11.25, 11.75, 1.25, 11.25, 11.25, 8.49, 10.98, 8.75, 1.25, 8.75, 8.49, 8.49, 1.5, 1.5, 8.75, 4.45, 11.25, 1.25, 11.75, 8.49, 2.39, 9.25, 4.45, 9.25, 8.75, 8.99, 1.69, 17.5, 2.39, 8.99, 8.99, 11.25, 4.45, 8.75, 4.45, 9.25, 6.49, 10.98, 8.49, 8.49, 1.09, 1.69, 9.25, 4.45, 8.75, 1.25, 2.95, 3.99, 8.49, 11.75, 11.75, 2.15, 11.48, 8.75, 2.15, 1.25, 11.25, 2.15, 1.25, 8.75, 8.75, 6.49, 1.69, 8.99, 8.75, 11.75, 10.98, 1.09, 8.49, 3.39, 8.75, 2.15, 1.25, 11.48, 10.98, 10.98, 8.49, 2.95, 9.25, 9.25, 11.75, 4.45, 11.48, 11.25, 8.75, 4.45, 1.69, 8.99, 8.75, 4.45, 1.5, 11.75, 2.15, 8.99, 2.39, 8.75, 2.95, 1.25, 8.75, 2.15, 1.25, 2.18, 2.18, 11.48, 8.75, 2.95, 11.75, 11.75, 1.25, 10.58, 8.99, 2.39, 11.75, 4.45, 11.25, 11.25, 17.5, 8.75, 8.75, 8.75, 22.5, 9.25, 8.75, 4.45, 11.75, 1.25, 11.25, 11.25, 2.95, 8.99, 1.69, 11.25, 4.45, 8.75, 6.49, 8.75, 4.45, 9.25, 4.45, 11.75, 11.75, 4.45, 11.89, 11.75, 11.25, 2.95, 1.5, 4.45, 8.75, 8.99, 1.09, 8.99, 1.09, 3.99, 11.48, 8.49, 9.25, 4.45, 11.48, 9.25, 2.95, 9.25, 8.49, 8.99, 8.99, 8.49, 8.75, 2.95, 4.45, 11.89, 10.58, 8.19, 1.69, 8.75, 2.15, 1.25, 17.5, 6.49, 9.25, 2.15, 8.75, 4.45, 8.75, 1.25, 11.48, 11.48, 8.99, 2.18, 8.49, 8.99, 2.39, 2.39, 2.18, 8.75, 4.45, 11.25, 9.25, 9.25, 11.25, 11.25, 4.45, 2.95, 11.75, 8.49, 8.49, 8.99, 1.69, 9.25, 11.25, 11.75, 9.25, 8.75, 11.75, 8.75, 8.75, 11.25, 11.25, 10.98, 11.25, 4.45, 10.98, 8.49, 8.99, 3.39, 3.99, 8.99, 1.09, 1.09, 2.39, 17.5, 4.45, 11.25, 11.25, 4.45, 9.25, 4.45, 8.75, 2.15, 1.25, 11.89, 2.95, 11.75, 1.25, 11.25, 4.45, 11.48, 11.48, 2.95, 9.25, 8.75, 9.25, 2.95, 11.25, 1.25, 11.75, 1.25, 8.99, 2.39, 1.25, 11.25, 1.25, 11.25, 8.49, 3.99, 35.0, 27.75, 8.75, 11.8, 8.9, 5.9, 6.49, 10.98, 17.98, 2.39, 9.25, 8.75, 2.15, 8.75, 4.45, 8.49, 1.69, 8.19, 8.69, 10.98, 3.99, 11.48, 11.48, 4.45, 8.75, 6.49, 8.75, 8.75, 9.25, 1.25, 4.45, 8.49, 1.69, 9.25, 4.45, 8.99, 1.09, 11.25, 2.95, 11.08, 11.08, 3.89, 10.98, 11.25, 8.75, 11.25, 9.25, 4.3, 8.75, 8.49, 3.99, 1.69, 8.99, 8.49, 1.69, 11.75, 11.25, 11.89, 9.25, 2.95, 9.25, 2.95, 8.75, 4.45, 4.45, 8.75, 10.98, 11.48, 8.49, 9.25, 4.45, 11.75, 11.89, 8.99, 8.49, 8.75, 9.25, 8.75, 8.75, 11.75, 11.75, 4.45, 11.25, 11.75, 2.5, 8.99, 1.69, 11.75, 2.15, 1.25, 9.25, 8.75, 8.9, 9.25, 2.95, 8.75, 11.25, 8.9, 11.25, 11.75, 11.48, 1.69, 3.39, 9.25, 2.95, 8.99, 1.69, 8.49, 10.98, 11.25, 2.95, 8.99, 1.69, 8.75, 2.15, 1.25, 8.75, 2.95, 9.25, 2.5, 11.25, 1.25, 11.75, 2.5, 11.25, 1.5, 8.75, 1.25, 2.95, 11.48, 11.48, 8.75, 8.75, 2.15, 11.75, 1.25, 9.25, 9.25, 6.49, 11.75, 8.49, 8.49, 1.09, 10.98, 8.75, 1.25, 2.15, 11.25, 1.5, 11.25, 11.25, 8.49, 8.49, 8.75, 1.5, 1.25, 1.5, 8.75, 2.5, 2.15, 7.4, 7.4, 4.0, 9.25, 9.39, 9.25, 9.25, 9.39, 11.25, 8.9, 11.25, 6.0, 11.25, 11.25, 11.25, 22.5, 11.48, 1.09, 8.49, 8.49, 17.5, 11.25, 1.5, 9.25, 8.75, 3.99, 8.49, 8.75, 8.75, 8.75, 8.75, 8.75, 11.75, 1.5, 11.25, 11.25, 2.95, 8.99, 10.98, 9.25, 8.75, 4.45, 8.49, 1.09, 2.39, 8.75, 8.75, 11.48, 8.99, 8.49, 8.49, 2.39, 10.98, 8.49, 3.99, 11.75, 4.45, 8.75, 2.15, 1.25, 10.98, 8.99, 11.25, 1.5, 8.75, 2.15, 1.25, 8.75, 9.25, 8.75, 11.25, 1.5, 8.75, 1.25, 4.45, 10.98, 8.75, 2.95, 1.25, 8.75, 2.95, 1.25, 8.49, 8.49, 2.39, 11.25, 1.25, 8.75, 8.75, 9.25, 8.75, 11.89, 1.25, 8.75, 2.15, 1.25, 8.99, 1.09, 8.75, 4.45, 26.25, 8.75, 4.45, 11.75, 2.95, 8.75, 8.75, 11.75, 8.75, 11.25, 11.25, 11.25, 4.45, 1.25, 8.49, 8.49, 8.49, 8.99, 8.99, 2.39, 2.39, 3.99, 8.75, 4.45, 2.15, 9.25, 1.25, 11.25, 11.75, 8.75, 4.45, 11.25, 2.15, 8.75, 4.45, 8.75, 8.75, 1.25, 11.25, 2.15, 8.75, 5.9, 11.75, 1.25, 9.25, 3.75, 8.75, 1.25, 4.45, 11.75, 4.45, 8.75, 23.5, 8.75, 2.95, 8.75, 8.75, 11.89, 4.45, 2.95, 1.25, 8.75, 4.45, 2.95, 1.25, 8.75, 2.15, 1.25, 11.75, 2.95, 8.99, 3.39, 9.25, 9.25, 17.5, 2.95, 11.89, 1.5, 11.25, 2.95, 9.25, 11.25, 11.25, 2.95, 8.75, 9.25, 4.3, 8.75, 8.75, 11.25, 8.75, 4.3, 8.75, 1.25, 2.15, 8.49, 8.49, 3.39, 3.39, 10.98, 10.98, 2.39, 11.25, 11.75, 11.75, 1.25, 5.9, 8.75, 11.25, 9.25, 4.45, 1.5, 3.39, 8.99, 2.39, 11.25, 2.15, 11.25, 11.75, 11.75, 4.45, 11.75, 4.45, 9.25, 8.75, 8.49, 8.99, 8.49, 8.99, 11.75, 8.75, 8.49, 3.99, 3.89, 11.08, 8.49, 8.99, 8.49, 8.49, 8.49, 11.25, 2.15, 17.5, 8.75, 2.95, 8.49, 8.49, 10.98, 1.09, 11.25, 2.15, 2.95, 1.25, 8.75, 9.25, 9.25, 9.25, 2.95, 8.75, 2.15, 1.25, 8.99, 3.99, 11.75, 2.15, 8.99, 3.39, 9.25, 8.75, 11.25, 11.25, 4.45, 8.75, 2.15, 1.25, 11.75, 4.45, 9.25, 2.95, 8.49, 8.49, 11.25, 8.75, 4.45, 11.25, 11.25, 11.25, 11.25, 4.45, 8.49, 1.69, 8.49, 3.39, 8.75, 11.25, 9.25, 8.75, 11.25, 11.25, 11.75, 11.25, 11.75, 11.25, 11.75, 21.96, 10.98, 1.69, 11.48, 8.99, 8.49, 1.69, 9.25, 2.15, 1.5, 11.25, 1.5, 8.75, 8.75, 2.95, 8.49, 1.69, 8.75, 2.95, 1.25, 11.25, 2.15, 11.08, 8.49, 8.49, 8.49, 11.75, 1.25, 11.75, 8.75, 8.75, 8.75, 4.45, 11.25, 1.5, 23.5, 11.75, 6.49, 8.75, 4.45, 6.49, 8.75, 2.5, 2.15, 8.49, 2.39, 8.75, 11.75, 4.45, 8.99, 10.98, 9.25, 2.95, 9.25, 9.25, 11.75, 8.75, 8.75, 8.75, 10.98, 11.25, 9.25, 8.75, 8.75, 2.15, 11.25, 2.15, 4.45, 11.75, 8.49, 2.39, 9.25, 1.25, 1.25, 1.25, 1.25, 8.75, 2.15, 8.49, 1.69, 11.25, 1.5, 8.75, 8.75, 8.49, 3.99, 8.99, 1.09, 11.25, 1.25, 8.49, 2.39, 8.49, 8.75, 9.25, 11.25, 4.45, 11.25, 11.89, 8.99, 8.49, 8.75, 4.45, 8.75, 11.75, 11.75, 8.9, 9.39, 2.95, 8.49, 3.99, 8.75, 2.15, 1.25, 21.96, 8.49, 1.69, 8.75, 4.45, 8.49, 8.99, 8.49, 3.99, 8.75, 8.75, 2.95, 8.75, 17.5, 9.25, 2.95, 8.75, 6.49, 4.3, 8.75, 8.75, 2.15, 1.5, 8.49, 8.49, 2.39, 9.25, 4.45, 6.49, 11.75, 4.45, 10.98, 1.69, 9.39, 9.25, 9.25, 2.95, 8.75, 2.15, 1.25, 11.25, 9.25, 8.75, 11.25, 8.75, 11.25, 2.5, 2.5, 6.0, 8.9, 5.9, 11.25, 11.25, 8.49, 10.98, 8.75, 2.15, 1.5, 9.25, 1.25, 1.5, 2.15, 1.25, 8.75, 2.95, 8.49, 3.99, 11.25, 4.3, 11.75, 2.15, 18.5, 8.49, 2.39, 8.75, 4.45, 11.75, 8.99, 3.99, 9.25, 9.25, 1.5, 8.75, 2.95, 6.49, 11.75, 8.49, 8.99, 8.75, 4.45, 6.49, 22.5, 9.25, 2.95, 8.49, 1.69, 10.98, 8.75, 4.45, 11.25, 2.95, 8.99, 8.49, 2.39, 11.75, 6.49, 11.25, 11.75, 2.95, 8.99, 1.69, 8.99, 2.18, 1.09, 8.99, 8.99, 1.09, 8.99, 8.99, 8.49, 10.98, 1.09, 11.75, 9.25, 11.25, 11.25, 2.15, 11.25, 8.75, 4.45, 2.95, 11.75, 1.5, 8.99, 10.98, 2.39, 8.75, 2.15, 9.25, 1.5, 8.75, 2.15, 3.99, 8.99, 6.49, 8.75, 8.9, 8.99, 3.99, 17.5, 11.25, 1.25, 10.98, 9.25, 4.45, 1.25, 3.0, 11.25, 4.45, 4.45, 2.95, 9.25, 11.25, 2.15, 11.25, 11.25, 4.45, 2.95, 9.25, 11.25, 1.25, 8.75, 2.95, 1.25, 8.75, 4.45, 11.48, 11.48, 8.49, 2.39, 11.25, 11.75, 2.15, 1.5, 2.15, 8.75, 11.25, 8.9, 11.25, 11.25, 1.25, 4.45, 9.25, 9.25, 8.75, 9.25, 8.75, 8.75, 9.25, 8.75, 11.75, 11.75, 8.75, 8.75, 8.9, 2.95, 10.98, 8.49, 8.49, 10.98, 8.99, 8.99, 11.75, 17.5, 11.75, 3.99, 8.49, 10.98, 1.69, 17.5, 8.99, 2.39, 8.99, 2.39, 1.25, 8.75, 2.95, 11.75, 11.25, 17.5, 8.49, 8.49, 2.39, 11.25, 1.5, 8.75, 3.0, 1.25, 8.75, 4.45, 11.75, 11.75, 4.45, 21.96, 8.75, 4.45, 8.75, 11.25, 9.25, 8.99, 2.39, 9.25, 8.75, 10.98, 8.49, 3.99, 3.39, 11.75, 1.5, 4.45, 9.25, 8.75, 1.25, 11.75, 8.75, 1.5, 8.75, 8.75, 2.15, 1.5, 8.75, 2.95, 8.75, 8.75, 17.5, 8.75, 6.49, 4.45, 11.25, 11.25, 4.3, 8.75, 11.25, 4.45, 8.99, 2.39, 9.25, 9.25, 9.25, 4.45, 11.75, 11.25, 2.95, 2.15, 11.25, 11.25, 8.75, 2.15, 1.5, 9.25, 4.45, 10.98, 8.99, 2.18, 8.75, 4.45, 1.25, 8.99, 2.39, 4.45, 8.75, 10.98, 11.75, 1.5, 10.98, 8.99, 8.49, 3.99, 8.99, 8.49, 3.99, 8.49, 8.49, 8.99, 11.25, 11.25, 10.98, 10.98, 10.98, 2.39, 3.39, 8.75, 1.25, 2.95, 11.75, 1.5, 10.98, 1.69, 4.45, 8.75, 8.75, 8.75, 8.75, 4.45, 9.25, 8.75, 11.25, 8.75, 3.99, 8.99, 8.49, 11.25, 11.25, 8.75, 4.45, 8.75, 4.45, 1.25, 8.75, 8.75, 1.5, 2.15, 11.75, 11.75, 11.75, 11.75, 11.75, 1.5, 8.75, 9.25, 1.25, 8.75, 2.15, 8.99, 1.09, 4.45, 11.25, 11.75, 2.15, 8.75, 8.75, 1.25, 9.25, 2.15, 11.75, 11.25, 8.75, 11.25, 4.45, 8.49, 1.69, 8.75, 8.75, 8.99, 8.49, 9.25, 11.25, 2.95, 4.45, 11.75, 6.49, 11.48, 8.99, 4.36, 11.48, 8.99, 8.49, 11.48, 8.75, 2.15, 1.5, 8.99, 1.69, 11.25, 1.25, 9.25, 9.25, 8.75, 9.25, 8.9, 2.15, 9.25, 10.98, 8.49, 8.75, 9.25, 4.3, 9.25, 8.75, 8.75, 2.15, 1.25, 8.75, 1.25, 8.75, 5.9, 9.25, 8.75, 9.25, 4.45, 9.25, 11.75, 2.5, 9.25, 2.15, 9.25, 1.5, 1.25, 11.25, 2.95, 8.75, 8.75, 8.75, 10.98, 8.75, 8.75, 8.75, 2.15, 1.25, 10.98, 8.75, 2.15, 1.5, 8.75, 2.95, 1.25, 9.25, 9.25, 8.49, 2.39, 8.75, 4.45, 9.25, 8.75, 8.75, 8.75, 9.25, 8.75, 9.25, 8.75, 8.75, 8.75, 8.75, 9.25, 8.75, 9.25, 8.75, 9.25, 8.75, 8.75, 8.75, 9.25, 8.75, 9.25, 8.75, 8.99, 8.99, 8.75, 2.95, 1.25, 11.75, 1.5, 11.25, 11.25, 8.75, 1.5, 2.15, 16.98, 11.75, 1.5, 8.75, 4.3, 1.5, 8.75, 2.95, 1.25, 1.25, 9.25, 4.45, 11.25, 8.75, 4.45, 8.75, 2.15, 1.25, 10.98, 1.69, 8.75, 1.25, 8.75, 1.25, 11.25, 8.75, 8.75, 8.49, 1.69, 9.25, 11.75, 8.49, 2.39, 9.25, 2.95, 6.49, 8.75, 8.75, 9.25, 8.75, 6.78, 17.98, 3.39, 11.75, 11.25, 8.75, 4.45, 11.75, 9.25, 8.75, 6.49, 8.99, 2.39, 8.75, 11.25, 11.75, 4.45, 8.75, 2.15, 9.25, 9.25, 9.25, 11.89, 11.75, 11.25, 9.25, 9.25, 8.75, 8.75, 8.49, 1.69, 1.09, 11.25, 1.5, 11.25, 11.25, 11.75, 1.5, 8.49, 8.99, 22.5, 8.75, 4.3, 8.75, 11.25, 2.15, 11.25, 2.95, 4.45, 11.25, 8.49, 3.39, 2.39, 11.75, 2.15, 11.75, 8.99, 2.39, 8.75, 11.75, 11.89, 1.25, 7.5, 11.89, 1.09, 8.49, 2.39, 8.75, 8.75, 8.75, 8.75, 9.25, 11.25, 8.75, 8.9, 9.25, 8.75, 8.75, 11.75, 3.0, 1.5, 11.25, 11.75, 8.99, 10.98, 4.45, 8.75, 2.15, 9.25, 11.25, 4.45, 1.69, 10.98, 9.25, 11.75, 9.25, 4.45, 10.98, 3.99, 8.49, 1.25, 9.25, 4.45, 10.98, 8.75, 8.75, 11.75, 11.25, 8.49, 11.48, 4.45, 1.25, 11.25, 8.99, 1.09, 2.39, 11.25, 2.15, 8.75, 4.45, 8.49, 1.69, 10.98, 1.69, 9.25, 4.45, 11.25, 8.75, 11.25, 11.75, 11.25, 22.5, 8.49, 2.39, 2.5, 8.75, 8.75, 9.25, 9.25, 11.25, 8.99, 1.09, 8.99, 1.69, 11.75, 1.25, 21.96, 8.75, 2.15, 1.25, 8.75, 11.25, 9.25, 11.25, 8.75, 8.75, 11.25, 2.15, 8.99, 1.09, 1.69, 8.75, 2.15, 1.25, 8.49, 1.09, 1.09, 1.69, 11.48, 8.49, 8.49, 4.78, 9.25, 1.25, 1.25, 1.25, 11.25, 11.25, 11.75, 4.45, 11.25, 4.45, 8.99, 1.09, 11.25, 2.15, 11.25, 9.25, 11.75, 11.25, 11.25, 9.25, 2.95, 11.25, 4.45, 8.75, 2.95, 2.95, 11.25, 1.5, 10.98, 16.98, 18.5, 10.98, 3.99, 1.09, 9.25, 9.25, 8.75, 4.45, 17.5, 8.75, 4.45, 8.75, 1.25, 4.45, 9.25, 8.75, 8.75, 17.5, 4.45, 9.39, 1.25, 2.95, 11.25, 8.75, 8.75, 11.25, 2.15, 8.9, 11.25, 11.89, 10.98, 11.25, 4.45, 11.25, 11.25, 8.49, 10.98, 8.49, 3.39, 9.25, 8.75, 2.95, 3.0, 9.39, 11.75, 2.95, 1.5, 11.25, 11.75, 8.75, 2.15, 1.5, 8.49, 3.39, 11.75, 1.25, 17.5, 11.25, 1.25, 8.75, 2.95, 1.25, 11.25, 11.75, 13.35, 11.25, 11.75, 11.25, 11.25, 4.45, 11.25, 8.49, 3.39, 9.25, 2.95, 4.78, 2.39, 3.99, 8.99, 8.99, 11.25, 11.25, 8.75, 11.25, 2.95, 4.45, 9.25, 8.75, 4.45, 8.49, 8.49, 10.98, 10.98, 3.99, 11.75, 8.75, 11.75, 4.45, 1.5, 1.25, 8.49, 8.49, 8.75, 8.75, 8.75, 9.25, 8.75, 2.95, 1.25, 11.25, 1.5, 11.25, 4.45, 9.25, 8.75, 8.75, 9.25, 8.75, 4.45, 1.5, 8.75, 8.75, 8.49, 1.69, 8.75, 2.15, 9.25, 2.15, 1.5, 11.25, 11.75, 2.15, 6.49, 9.25, 9.25, 11.25, 11.25, 11.75, 11.75, 11.75, 11.25, 8.75, 2.15, 1.25, 11.75, 9.25, 11.25, 8.75, 5.9, 8.75, 4.45, 9.25, 9.25, 4.45, 11.25, 4.45, 11.25, 8.75, 2.15, 11.89, 11.25, 8.75, 2.95, 1.5, 8.75, 4.3, 8.75, 11.25, 11.75, 11.75, 2.15, 11.25, 8.99, 1.09, 8.49, 8.49, 8.49, 3.39, 8.99, 10.98, 3.99, 11.75, 2.15, 8.75, 4.45, 2.5, 11.48, 1.09, 8.49, 8.49, 16.98, 3.99, 10.98, 1.09, 8.75, 2.95, 8.75, 8.75, 2.95, 9.25, 11.25, 2.15, 9.25, 4.45, 4.45, 9.25, 11.75, 11.75, 2.15, 9.25, 8.75, 11.25, 6.49, 8.75, 11.25, 2.95, 10.98, 3.99, 1.5, 9.25, 2.15, 8.75, 11.25, 11.89, 4.45, 1.5, 1.25, 8.75, 8.75, 4.45, 11.25, 11.75, 8.49, 1.09, 1.09, 1.69, 8.99, 3.39, 8.99, 1.69, 8.49, 8.99, 3.27, 8.99, 8.99, 1.09, 10.98, 1.69, 3.99, 8.49, 1.09, 8.75, 8.75, 11.75, 8.75, 9.25, 8.75, 3.39, 8.99, 8.99, 2.39, 9.25, 8.75, 9.25, 9.25, 8.99, 3.99, 2.39, 8.49, 1.09, 8.49, 8.99, 3.39, 11.25, 1.25, 8.99, 3.99, 8.75, 8.9, 6.49, 8.75, 9.25, 11.25, 11.25, 11.25, 1.25, 8.75, 9.25, 4.45, 1.25, 8.75, 1.25, 2.15, 17.98, 8.99, 8.75, 2.95, 1.25, 11.75, 1.5, 1.5, 8.75, 8.75, 11.08, 8.99, 1.69, 8.99, 1.69, 10.98, 3.99, 3.39, 11.75, 2.15, 11.75, 2.95, 8.75, 8.75, 11.75, 11.25, 11.75, 11.25, 4.45, 11.25, 1.25, 2.18, 2.18, 2.39, 8.49, 8.99, 2.39, 11.25, 8.75, 11.75, 11.75, 11.25, 4.45, 2.15, 8.19, 10.58, 4.45, 9.25, 1.09, 8.99, 11.25, 1.5, 8.99, 3.99, 4.45, 11.75, 2.15, 11.25, 8.75, 4.45, 8.75, 9.25, 6.45, 8.75, 11.25, 11.25, 8.75, 11.75, 21.96, 8.99, 5.07, 8.49, 9.25, 11.25, 4.45, 3.39, 8.49, 8.99, 8.49, 17.5, 22.96, 8.75, 11.25, 11.89, 11.25, 8.49, 1.69, 1.09, 8.99, 8.99, 9.25, 8.75, 9.25, 2.95, 8.49, 3.99, 8.99, 8.49, 7.17, 8.49, 8.99, 17.5, 9.25, 9.25, 11.25, 1.25, 8.99, 1.09, 8.75, 4.45, 11.25, 2.15, 11.75, 11.25, 11.25, 8.75, 8.75, 4.45, 1.25, 11.75, 11.75, 2.5, 8.49, 8.99, 2.18, 11.25, 4.45, 11.25, 11.75, 8.49, 8.99, 1.69, 1.09, 8.99, 8.99, 11.25, 6.49, 11.25, 8.75, 4.45, 8.99, 1.69, 11.48, 11.75, 2.5, 8.49, 1.09, 1.09, 1.69, 8.49, 2.39, 11.75, 1.25, 8.49, 1.69, 8.49, 1.69, 11.75, 4.45, 8.75, 8.75, 4.45, 8.75, 11.25, 11.25, 8.75, 7.98, 8.49, 1.09, 8.49, 3.99, 8.49, 3.99, 8.99, 3.99, 11.25, 4.45, 8.49, 2.39, 8.49, 2.39, 3.99, 8.49, 1.25, 11.25, 4.45, 9.25, 4.45, 1.09, 8.99, 3.99, 11.25, 8.9, 9.25, 11.25, 8.75, 11.25, 11.25, 11.25, 11.25, 11.25, 8.99, 8.49, 8.75, 8.75, 4.45, 16.98, 11.75, 11.25, 9.25, 4.45, 9.25, 2.95, 8.49, 1.69, 3.75, 4.45, 9.25, 1.5, 11.25, 11.48, 11.25, 2.15, 8.75, 9.39, 8.49, 3.99, 8.19, 2.29, 11.48, 1.69, 11.48, 3.99, 8.49, 1.69, 9.25, 2.95, 8.49, 1.69, 11.25, 4.45, 9.39, 9.25, 8.75, 8.75, 4.45, 11.89, 4.45, 4.45, 8.75, 8.75, 8.75, 2.15, 8.75, 3.75, 9.25, 11.25, 4.45, 6.49, 16.98, 18.5, 2.5, 2.95, 3.99, 8.49, 8.19, 11.08, 6.49, 11.75, 2.39, 8.99, 1.09, 11.25, 4.45, 11.25, 8.99, 1.69, 21.96, 2.18, 8.99, 8.99, 2.39, 8.69, 1.69, 8.9, 2.5, 8.75, 8.99, 1.09, 8.49, 8.49, 8.75, 4.45, 17.5, 8.75, 9.25, 8.49, 2.39, 8.75, 4.45, 11.25, 11.25, 11.75, 8.75, 8.49, 8.49, 8.49, 8.99, 8.75, 4.45, 11.48, 8.75, 1.25, 2.15, 9.25, 4.45, 11.75, 2.15, 11.25, 8.99, 2.39, 8.69, 8.69, 11.75, 2.95, 11.75, 1.5, 9.25, 4.45, 1.5, 11.48, 8.99, 2.39, 11.25, 11.89, 2.15, 1.25, 11.75, 4.45, 8.75, 8.75, 11.25, 4.45, 11.25, 2.15, 4.45, 8.49, 1.09, 3.99, 11.25, 11.25, 8.49, 2.39, 8.99, 2.39, 11.25, 2.15, 8.75, 2.95, 1.25, 8.75, 11.2

In [ ]:
df_chipotle

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [ ]:
df_chipotle[df_chipotle.item_price < 8]

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
6,3,1,Side of Chips,NaN,1.69
...,...,...,...,...,...
4606,1828,1,Canned Soft Drink,[Coke],1.25
4609,1829,1,Canned Soft Drink,[Sprite],1.25
4613,1831,1,Chips,NaN,2.15
4614,1831,1,Bottled Water,NaN,1.50
4616,1832,1,Chips and Guacamole,NaN,4.45

In [ ]:
df_chipotle[(df_chipotle.item_name == 'Chips') | (df_chipotle.item_price > 2)]

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [ ]:
df_chipotle[(df_chipotle.item_name.str.contains('Drink', na=False))]

      order_id  quantity          item_name choice_description  item_price
263        114         1  Canned Soft Drink             [Coke]        1.25
292        127         1  Canned Soft Drink           [Sprite]        1.25
298        129         1  6 Pack Soft Drink           [Sprite]        6.49
320        139         1  Canned Soft Drink             [Coke]        1.25
337        147         1  Canned Soft Drink             [Coke]        1.25
...        ...       ...                ...                ...         ...
4585      1823         1  Canned Soft Drink        [Diet Coke]        1.25
4597      1826         1  Canned Soft Drink           [Nestea]        1.25
4601      1827         1  Canned Soft Drink        [Diet Coke]        1.25
4606      1828         1  Canned Soft Drink             [Coke]        1.25
4609      1829         1  Canned Soft Drink           [Sprite]        1.25

[355 rows x 5 columns]

In [ ]:
df_chipotle[(df_chipotle.choice_description.str.contains('Rice', na=False))]

,order_id,quantity,item_name,choice_description,item_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",9.25
11,6,1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
12,6,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",8.75
...,...,...,...,...,...
4611,1830,1,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",11.25
4612,1831,1,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",9.25
4615,1832,1,Chicken Soft Tacos,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",8.75
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75

In [ ]:
import pandas as pd
euro12 = pd.read_csv('Euro2012TEAM.csv')
euro12

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,6,66.7%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,...,13,76.5%,48,31,4,5,0,9,9,18

task

      1. Select only the Goal column
      2. How many team participated in the Euro2012?
      3. What is the number of columns in the dataset?
      4. View only the columns Team, Yellow Cards and Red Cards and assign them to a dataframe called discipline
      5. Sort the teams by Red Cards, then to Yellow Cards
      6. Calculate the mean Yellow Cards given per Team
      7. Filter teams that scored more than 6 goals
      8. Select the teams that start with G
      9. Select the first 7 columns
      10. Select all columns except the last 3.
      11. Present only the Shooting Accuracy from England, Italy and Russia

In [ ]:
euro12.Goals

0      4
1      4
2      4
3      5
4      3
5     10
6      5
7      6
8      2
9      2
10     6
11     1
12     5
13    12
14     5
15     2
Name: Goals, dtype: int64

In [ ]:
euro12.Team.count()

16

In [ ]:
euro12.columns, euro12.info

(Index(['Team', 'Goals', 'Shots on target', 'Shots off target',
        'Shooting Accuracy', '% Goals-to-shots', 'Total shots (inc. Blocked)',
        'Hit Woodwork', 'Penalty goals', 'Penalties not scored', 'Headed goals',
        'Passes', 'Passes completed', 'Passing Accuracy', 'Touches', 'Crosses',
        'Dribbles', 'Corners Taken', 'Tackles', 'Clearances', 'Interceptions',
        'Clearances off line', 'Clean Sheets', 'Blocks', 'Goals conceded',
        'Saves made', 'Saves-to-shots ratio', 'Fouls Won', 'Fouls Conceded',
        'Offsides', 'Yellow Cards', 'Red Cards', 'Subs on', 'Subs off',
        'Players Used'],
       dtype='object'),
 <bound method DataFrame.info of                    Team  Goals  Shots on target  Shots off target  \
 0               Croatia      4               13                12
 1        Czech Republic      4               13                18
 2               Denmark      4               10                10
 3               England      5               11                18
 4                France      3               22                24
 5               Germany     10               32                32
 6                Greece      5                8                18
 7                 Italy      6               34                45
 8           Netherlands      2               12                36
 9                Poland      2               15                23
 10             Portugal      6               22                42
 11  Republic of Ireland      1                7                12
 12               Russia      5                9                31
 13                Spain     12               42                33
 14               Sweden      5               17                19
 15              Ukraine      2                7                26

    Shooting Accuracy % Goals-to-shots  Total shots (inc. Blocked)  \
 0              51.9%            16.0%                          32
 1              41.9%            12.9%                          39
 2              50.0%            20.0%                          27
 3              50.0%            17.2%                          40
 4              37.9%             6.5%                          65
 5              47.8%            15.6%                          80
 6              30.7%            19.2%                          32
 7              43.0%             7.5%                         110
 8              25.0%             4.1%                          60
 9              39.4%             5.2%                          48
 10             34.3%             9.3%                          82
 11             36.8%             5.2%                          28
 12             22.5%            12.5%                          59
 13             55.9%            16.0%                         100
 14             47.2%            13.8%                          39
 15             21.2%             6.0%                          38

     Hit Woodwork  Penalty goals  Penalties not scored  ...  Saves made  \
 0              0              0                     0  ...          13
 1              0              0                     0  ...           9
 2              1              0                     0  ...          10
 3              0              0                     0  ...          22
 4              1              0                     0  ...           6
 5              2              1                     0  ...          10
 6              1              1                     1  ...          13
 7              2              0                     0  ...          20
 8              2              0                     0  ...          12
 9              0              0                     0  ...           6
 10             6              0                     0  ...          10
 11             0              0                     0  ...          17
 12             2              0                     0  ...          10
 13             0              1                     0  ...          15
 14             3              0                     0  ...           8
 15             0              0                     0  ...          13

     Saves-to-shots ratio  Fouls Won Fouls Conceded  Offsides  Yellow Cards  \
 0                  81.3%         41             62         2             9
 1                  60.1%         53             73         8             7
 2                  66.7%         25             38         8             4
 3                  88.1%         43             45         6             5
 4                  54.6%         36             51         5             6
 5                  62.6%         63             49        12             4
 6                  65.1%         67             48        12             9
 7                  74.1%        101             89        16            16
 8                  70.6%         35             30         3             5
 9                  66.7%         48             56         3             7
 10                 71.5%         73             90        10            12
 11                 65.4%         43             51        11             6
 12                 77.0%         34             43         4             6
 13                 93.8%        102             83        19            11
 14                 61.6%         35             51         7             7
 15                 76.5%         48             31         4             5

     Red Cards  Subs on  Subs off  Players Used
 0           0        9         9            16
 1           0       11        11            19
 2           0        7         7            15
 3           0       11        11            16
 4           0       11        11            19
 5           0       15        15            17
 6           1       12        12            20
 7           0       18        18            19
 8           0        7         7            15
 9           1        7         7            17
 10          0       14        14            16
 11          1       10        10            17
 12          0        7         7            16
 13          0       17        17            18
 14          0        9         9            18
 15          0        9         9            18

 [16 rows x 35 columns]>)

In [ ]:
discipline = euro12[['Team','Yellow Cards', 'Red Cards']]
discipline

                   Team  Yellow Cards  Red Cards
0               Croatia             9          0
1        Czech Republic             7          0
2               Denmark             4          0
3               England             5          0
4                France             6          0
5               Germany             4          0
6                Greece             9          1
7                 Italy            16          0
8           Netherlands             5          0
9                Poland             7          1
10             Portugal            12          0
11  Republic of Ireland             6          1
12               Russia             6          0
13                Spain            11          0
14               Sweden             7          0
15              Ukraine             5          0

In [ ]:
discipline.sort_values(['Red Cards', 'Yellow Cards'], ascending = False)

                   Team  Yellow Cards  Red Cards
6                Greece             9          1
9                Poland             7          1
11  Republic of Ireland             6          1
7                 Italy            16          0
10             Portugal            12          0
13                Spain            11          0
0               Croatia             9          0
1        Czech Republic             7          0
14               Sweden             7          0
4                France             6          0
12               Russia             6          0
3               England             5          0
8           Netherlands             5          0
15              Ukraine             5          0
2               Denmark             4          0
5               Germany             4          0

In [ ]:
round(discipline['Yellow Cards'].mean())

7

In [ ]:
euro12[euro12.Goals > 6]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18

In [ ]:
euro12[euro12['Penalty goals']>=1]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18

In [ ]:
euro12[euro12['Hit Woodwork']>=1]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,12,70.6%,35,30,3,5,0,7,7,15
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,10,71.5%,73,90,10,12,0,14,14,16
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,10,77.0%,34,43,4,6,0,7,7,16
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,8,61.6%,35,51,7,7,0,9,9,18

In [ ]:
euro12[euro12.Team.str.startswith('G')]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20

In [ ]:
euro12.iloc[: , 0:7]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked)
0,Croatia,4,13,12,51.9%,16.0%,32
1,Czech Republic,4,13,18,41.9%,12.9%,39
2,Denmark,4,10,10,50.0%,20.0%,27
3,England,5,11,18,50.0%,17.2%,40
4,France,3,22,24,37.9%,6.5%,65
5,Germany,10,32,32,47.8%,15.6%,80
6,Greece,5,8,18,30.7%,19.2%,32
7,Italy,6,34,45,43.0%,7.5%,110
8,Netherlands,2,12,36,25.0%,4.1%,60
9,Poland,2,15,23,39.4%,5.2%,48
10,Portugal,6,22,42,34.3%,9.3%,82
11,Republic of Ireland,1,7,12,36.8%,5.2%,28
12,Russia,5,9,31,22.5%,12.5%,59
13,Spain,12,42,33,55.9%,16.0%,100
14,Sweden,5,17,19,47.2%,13.8%,39
15,Ukraine,2,7,26,21.2%,6.0%,38

In [ ]:
# loc(st_row:end_row, st_col:end_col)
euro12.loc[euro12.Team.isin(['England', 'Italy', 'Russia']), ['Team','Shooting Accuracy']]

       Team Shooting Accuracy
3   England             50.0%
7     Italy             43.0%
12   Russia             22.5%